/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.User;

import Interface.MainBlankJPanel;
import System.EcoSystem;
import System.Enterprise.AdExchange;
import System.Enterprise.Enterprise;
import System.Market.Market;
import System.Network.Network;
import System.Person.AddressInfo;
import System.Person.EndUserPersonProfile;
import System.Role.UserRole;
import System.UserAccount.EndUserUserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.Calendar;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author SURAJ
 */
public class NewUserSignUpJPanel extends javax.swing.JPanel {

     private EcoSystem system;
     private JPanel userProcessContainer;
    /**
     * Creates new form NewUserSignUpJPanel
     */
    public NewUserSignUpJPanel(JPanel userProcessContainer,EcoSystem system) {
        initComponents();
        this.system= system;
        this.userProcessContainer= userProcessContainer;
        populateComboBox();
        populateInterestComboBox();
    }

      private void populateComboBox()
    {
        networkJComboBox1.removeAllItems();
        for(Network n: system.getNetworkList())
          networkJComboBox1.addItem(n);
    }
     private void populateInterestComboBox()
    {
        interestsJComboBox1.removeAllItems();
        interestsJComboBox1.addItem(splitString(Market.SPORTS));
        interestsJComboBox1.addItem(splitString(Market.ELECTRONICS));
        interestsJComboBox1.addItem(splitString(Market.CLOTHING));
        interestsJComboBox1.addItem(splitString(Market.HEALTHMARKET));
    }
     private String splitString(String s)
     {
        String[] result = s.split(" ", 2);
        String first = result[0];
        return first;
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        createPersonJButton1 = new javax.swing.JButton();
        backJButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        firstNameJLabel10 = new javax.swing.JLabel();
        firstNameJTextField9 = new javax.swing.JTextField();
        lastNameJLabel9 = new javax.swing.JLabel();
        lastNameJTextField10 = new javax.swing.JTextField();
        dobJLabel12 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        dayJComboBox1 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        monthJComboBox2 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        yearsJTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        genderJComboBox1 = new javax.swing.JComboBox();
        ssnJLabel14 = new javax.swing.JLabel();
        personIDJTextField14 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        streetAddress1JLabel1 = new javax.swing.JLabel();
        streetAddress1JTextField1 = new javax.swing.JTextField();
        streetAddress2JLabel2 = new javax.swing.JLabel();
        streetAddress2JTextField2 = new javax.swing.JTextField();
        jcityJLabel3 = new javax.swing.JLabel();
        cityJTextField3 = new javax.swing.JTextField();
        stateJLabel4 = new javax.swing.JLabel();
        stateJTextField4 = new javax.swing.JTextField();
        zipCodeJLabel6 = new javax.swing.JLabel();
        countryJTextField1 = new javax.swing.JTextField();
        zipCodeJLabel5 = new javax.swing.JLabel();
        zipCodeJTextField5 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        interestsJComboBox1 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        usernameTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        confirmjPasswordField2 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        networkJComboBox1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        imageJLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/create icon.png"))); // NOI18N
        jLabel5.setText("New User Sign-up Form");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 330, 60));

        createPersonJButton1.setText("Create Profile");
        createPersonJButton1.setToolTipText("Create Person");
        createPersonJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createPersonJButton1.setEnabled(false);
        createPersonJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPersonJButton1ActionPerformed(evt);
            }
        });
        add(createPersonJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 530, -1, -1));

        backJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backbutton.png"))); // NOI18N
        backJButton1.setText("Back");
        backJButton1.setToolTipText("Back");
        backJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });
        add(backJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, 100, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Create Profile", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Apple Braille", 1, 14))); // NOI18N
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Step 1 of 3", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Apple Braille", 1, 14), new java.awt.Color(255, 0, 51))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(5, 2, 0, 4));

        firstNameJLabel10.setText("                  First Name");
        jPanel1.add(firstNameJLabel10);

        firstNameJTextField9.setPreferredSize(new java.awt.Dimension(7, 14));
        firstNameJTextField9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstNameJTextField9FocusLost(evt);
            }
        });
        jPanel1.add(firstNameJTextField9);

        lastNameJLabel9.setText("                  Last Name");
        jPanel1.add(lastNameJLabel9);

        lastNameJTextField10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastNameJTextField10FocusLost(evt);
            }
        });
        jPanel1.add(lastNameJTextField10);

        dobJLabel12.setText("                  Date of Birth");
        jPanel1.add(dobJLabel12);

        jPanel11.setOpaque(false);

        jLabel10.setText("Day :");
        jPanel11.add(jLabel10);

        dayJComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dayJComboBox1.setPreferredSize(new java.awt.Dimension(60, 27));
        jPanel11.add(dayJComboBox1);

        jLabel9.setText("Month :");
        jPanel11.add(jLabel9);

        monthJComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        monthJComboBox2.setPreferredSize(new java.awt.Dimension(105, 27));
        jPanel11.add(monthJComboBox2);

        jLabel2.setText("Year :");
        jPanel11.add(jLabel2);

        yearsJTextField2.setPreferredSize(new java.awt.Dimension(50, 28));
        yearsJTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                yearsJTextField2FocusLost(evt);
            }
        });
        jPanel11.add(yearsJTextField2);

        jPanel1.add(jPanel11);

        jLabel1.setText("                  Gender");
        jPanel1.add(jLabel1);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        genderJComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        jPanel3.add(genderJComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        jPanel1.add(jPanel3);

        ssnJLabel14.setText("                  Person ID");
        jPanel1.add(ssnJLabel14);

        personIDJTextField14.setToolTipText("");
        personIDJTextField14.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                personIDJTextField14FocusLost(evt);
            }
        });
        jPanel1.add(personIDJTextField14);

        jTabbedPane1.addTab("Personal Information", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Step 2 of 3", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Apple Braille", 1, 14), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(6, 2));

        streetAddress1JLabel1.setText("                 Street Address 1");
        jPanel2.add(streetAddress1JLabel1);
        jPanel2.add(streetAddress1JTextField1);

        streetAddress2JLabel2.setText("                 Street Address 2");
        jPanel2.add(streetAddress2JLabel2);
        jPanel2.add(streetAddress2JTextField2);

        jcityJLabel3.setText("                 City");
        jPanel2.add(jcityJLabel3);

        cityJTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cityJTextField3FocusLost(evt);
            }
        });
        jPanel2.add(cityJTextField3);

        stateJLabel4.setText("                 State");
        jPanel2.add(stateJLabel4);

        stateJTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                stateJTextField4FocusLost(evt);
            }
        });
        jPanel2.add(stateJTextField4);

        zipCodeJLabel6.setText("                 Country");
        jPanel2.add(zipCodeJLabel6);

        countryJTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                countryJTextField1FocusLost(evt);
            }
        });
        jPanel2.add(countryJTextField1);

        zipCodeJLabel5.setText("                 ZipCode");
        jPanel2.add(zipCodeJLabel5);

        zipCodeJTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                zipCodeJTextField5FocusLost(evt);
            }
        });
        jPanel2.add(zipCodeJTextField5);

        jTabbedPane1.addTab("Address Information", jPanel2);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Step 3 of 3", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Apple Braille", 1, 14), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.GridLayout(5, 2, 0, 4));

        jLabel12.setText("                 Likes and Interests :");
        jPanel6.add(jLabel12);

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Suggestions :");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 30));

        interestsJComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                interestsJComboBox1MouseClicked(evt);
            }
        });
        jPanel7.add(interestsJComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 160, 30));

        jPanel6.add(jPanel7);

        jLabel6.setText("                 Username :");
        jPanel6.add(jLabel6);

        usernameTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameTextField1FocusLost(evt);
            }
        });
        jPanel6.add(usernameTextField1);

        jLabel7.setText("                 Password :");
        jPanel6.add(jLabel7);
        jPanel6.add(jPasswordField1);

        jLabel11.setText("                 Confirm Password :");
        jPanel6.add(jLabel11);
        jPanel6.add(confirmjPasswordField2);
        jPanel6.add(jLabel4);
        jPanel6.add(jLabel13);

        jTabbedPane1.addTab("User Account Information", jPanel6);

        jPanel4.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, 310));

        networkJComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkJComboBox1ActionPerformed(evt);
            }
        });
        add(networkJComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 210, 30));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel8.setText("Select a Network :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 140, 30));

        imageJLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        imageJLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Organization Background.jpg"))); // NOI18N
        add(imageJLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 690));
    }// </editor-fold>//GEN-END:initComponents

    private void createPersonJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPersonJButton1ActionPerformed

        Network network = (Network) networkJComboBox1.getSelectedItem();
         if(network == null)
        {
             JOptionPane.showMessageDialog(null, "Please select a Network","Invalid Action", JOptionPane.WARNING_MESSAGE);
             return;
        }
        
       if(firstNameJTextField9.getText().isEmpty()||lastNameJTextField10.getText().isEmpty()||yearsJTextField2.getText().isEmpty()||
            personIDJTextField14.getText().isEmpty()||streetAddress1JTextField1.getText().isEmpty()||cityJTextField3.getText().isEmpty()
              ||stateJTextField4.getText().isEmpty()|| countryJTextField1.getText().isEmpty()
              ||zipCodeJTextField5.getText().isEmpty()|| usernameTextField1.getText().isEmpty())
       {
         JOptionPane.showMessageDialog(null, "One or more fields are Empty","", JOptionPane.INFORMATION_MESSAGE);
         return;
       }
       if(yearsJTextField2.getText().length()!=4||zipCodeJTextField5.getText().length()!=5
                ||personIDJTextField14.getText().length()!=6) return;
       if(yearsJTextField2.getText().contains("-")||zipCodeJTextField5.getText().contains("-")
                ||personIDJTextField14.getText().contains("-")||yearsJTextField2.getText().contains("+")
                ||zipCodeJTextField5.getText().contains("+")||personIDJTextField14.getText().contains("+")) return;
       int year,zipCode,personID;
        try{
            year = Integer.parseInt(yearsJTextField2.getText());
            zipCode= Integer.parseInt(zipCodeJTextField5.getText());
            personID= Integer.parseInt(personIDJTextField14.getText());
         } catch (Exception e) {return;
         }
          Boolean exists= system.checkPersonID(personID,system);
        if(!exists)
        {   
          String username= usernameTextField1.getText();
          char[] passchar = jPasswordField1.getPassword();
          String password = String.valueOf(passchar);
          if(!password.isEmpty()){
            char[] passcharconfirm = confirmjPasswordField2.getPassword();
            String confirmPassword = String.valueOf(passcharconfirm);
            if(password.equals(confirmPassword))
             {   
               Boolean usernameExists= system.checkUsername(username,system);
              if(!usernameExists){
                String day=  (String) dayJComboBox1.getSelectedItem();
                String month= (String) monthJComboBox2.getSelectedItem();
     
                Calendar now = Calendar.getInstance();
                int currentYear= now.get(Calendar.YEAR);
                int age = currentYear-year;
                AddressInfo address = new AddressInfo();
                address.setStreetAddress1(streetAddress1JTextField1.getText());
                address.setStreetAddress2(streetAddress2JTextField2.getText());
                address.setCity(cityJTextField3.getText());
                address.setState(stateJTextField4.getText());
                address.setCountry(countryJTextField1.getText());
                address.setZipCode(zipCode);
                EndUserPersonProfile person= new EndUserPersonProfile();
                person.setFirstName(firstNameJTextField9.getText());
                person.setLastName(lastNameJTextField10.getText());
                person.setPersonID(personID);
                person.setDay(Integer.parseInt(day));
                person.setMonth(month);
                person.setYear(year);
                person.setAge(age);
                person.setGender((String) genderJComboBox1.getSelectedItem());
                person.setAddress(address);
                person.setMarketType((String) interestsJComboBox1.getSelectedItem()+" Market");
                network.getUserOrganization().getPersonDirectory().getPersonlist().add(person);
                for(Enterprise enterprise: network.getEnterpriseList())
                 if(enterprise instanceof AdExchange)
                     ((AdExchange)enterprise).getUserPersonProfiles().getPersonlist().add(person);
                   
                   byte[] salt = network.getUserOrganization().getUserAccountDirectory().generateSalt();
                   String hashedPassword= network.getUserOrganization().getUserAccountDirectory().generateHashPassword(password, salt);
                   EndUserUserAccount userAccount= new EndUserUserAccount();
                   userAccount.setUsername(username);
                   userAccount.setPassword(hashedPassword);
                   userAccount.setSalt(salt);
                   userAccount.setRole(new UserRole());
                   userAccount.setPersonProfile(person);
                   network.getUserOrganization().getUserAccountDirectory().getUserAccountList().add(userAccount);
                   JOptionPane.showMessageDialog(null, "Profile Created Successfully","", JOptionPane.INFORMATION_MESSAGE);
                   MainBlankJPanel mainBlankJPanel= new MainBlankJPanel();
                   userProcessContainer.add("MainBlankJPanel",mainBlankJPanel);
                   ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
              }else  {
                    JOptionPane.showMessageDialog(null, "Please Enter different Username","Username already Exists", JOptionPane.ERROR_MESSAGE);
                    usernameTextField1.setBackground(Color.yellow);
                    usernameTextField1.setText("");
              }
             }else{
                   JOptionPane.showMessageDialog(null, "Password does not match","Re-enter Password", JOptionPane.ERROR_MESSAGE);
                   jPasswordField1.setBackground(Color.YELLOW);
                   confirmjPasswordField2.setBackground(Color.YELLOW);
                   jPasswordField1.setText("");
                   confirmjPasswordField2.setText("");
            }
           }else {
                  JOptionPane.showMessageDialog(null, "Please Enter a Password","Invalid Entry", JOptionPane.WARNING_MESSAGE);
                  jPasswordField1.setBackground(Color.YELLOW);
            }
        }else {
                 JOptionPane.showMessageDialog(null, "Please enter different PersonID","PersonID already exists", JOptionPane.ERROR_MESSAGE);
                 personIDJTextField14.setBackground(Color.yellow);
                 personIDJTextField14.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_createPersonJButton1ActionPerformed

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
         MainBlankJPanel mainBlankJPanel= new MainBlankJPanel();
         userProcessContainer.add("MainBlankJPanel",mainBlankJPanel);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_backJButton1ActionPerformed

    private void interestsJComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_interestsJComboBox1MouseClicked
        createPersonJButton1.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_interestsJComboBox1MouseClicked

    private void firstNameJTextField9FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameJTextField9FocusLost

        String value = firstNameJTextField9.getText();
        if (value.equals("")) {
        } else {
        Pattern pt6 = Pattern.compile("^[a-zA-Z]*$");
        Matcher mh6 = pt6.matcher(value);
        boolean matchFound6 = mh6.matches();
        if (!(matchFound6)) {
            JOptionPane.showMessageDialog(null, "Enter the Characters only");
            firstNameJTextField9.setText("");
            firstNameJTextField9.requestFocus();
        }
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameJTextField9FocusLost

    private void lastNameJTextField10FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameJTextField10FocusLost
        String value = lastNameJTextField10.getText();
        if (value.equals("")) {
        } else {
        Pattern pt6 = Pattern.compile("^[a-zA-Z]*$");
        Matcher mh6 = pt6.matcher(value);
        boolean matchFound6 = mh6.matches();
        if (!(matchFound6)) {
            JOptionPane.showMessageDialog(null, "Enter the Characters only");
            lastNameJTextField10.setText("");
            lastNameJTextField10.requestFocus();
        }
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameJTextField10FocusLost

    private void yearsJTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yearsJTextField2FocusLost
         String value = yearsJTextField2.getText();
        if (value.equals("")) {
        } else {
        Pattern pt6 = Pattern.compile("^[0-9]*$");
        Matcher mh6 = pt6.matcher(value);
        boolean matchFound6 = mh6.matches();
        if (!(matchFound6)) {
            JOptionPane.showMessageDialog(null, "Enter the Numbers only");
            yearsJTextField2.setText("");
            yearsJTextField2.requestFocus();
        }else{
            if(value.length()!=4)
            { JOptionPane.showMessageDialog(null, "Enter a valid Year value", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
                yearsJTextField2.setText("");
                yearsJTextField2.requestFocus();
            }
        }
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_yearsJTextField2FocusLost

    private void personIDJTextField14FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_personIDJTextField14FocusLost
        String value = personIDJTextField14.getText();
        if (value.equals("")) {
        } else {
        Pattern pt6 = Pattern.compile("^[0-9]*$");
        Matcher mh6 = pt6.matcher(value);
        boolean matchFound6 = mh6.matches();
        if (!(matchFound6)) {
            JOptionPane.showMessageDialog(null, "Enter the Numbers only");
            personIDJTextField14.setText("");
            personIDJTextField14.requestFocus();
        }else{
            if(value.length()!=6)
            { JOptionPane.showMessageDialog(null, "PersonID should be of 6 Digits");
                personIDJTextField14.setText("");
                personIDJTextField14.requestFocus();
            }
        }
    }   // TODO add your handling code here:
    }//GEN-LAST:event_personIDJTextField14FocusLost

    private void cityJTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cityJTextField3FocusLost
        String value = cityJTextField3.getText();
        if (value.equals("")) {
        } else {
        Pattern pt6 = Pattern.compile("^[a-zA-Z]*$");
        Matcher mh6 = pt6.matcher(value);
        boolean matchFound6 = mh6.matches();
        if (!(matchFound6)) {
            JOptionPane.showMessageDialog(null, "Enter the Characters only");
            cityJTextField3.setText("");
            cityJTextField3.requestFocus();
        }
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_cityJTextField3FocusLost

    private void stateJTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stateJTextField4FocusLost
      String value = stateJTextField4.getText();
        if (value.equals("")) {
        } else {
        Pattern pt6 = Pattern.compile("^[a-zA-Z]*$");
        Matcher mh6 = pt6.matcher(value);
        boolean matchFound6 = mh6.matches();
        if (!(matchFound6)) {
            JOptionPane.showMessageDialog(null, "Enter the Characters only");
            stateJTextField4.setText("");
            stateJTextField4.requestFocus();
        }
    }  // TODO add your handling code here:
    }//GEN-LAST:event_stateJTextField4FocusLost

    private void zipCodeJTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_zipCodeJTextField5FocusLost
        String value = zipCodeJTextField5.getText();
        if (value.equals("")) {
        } else {
        Pattern pt6 = Pattern.compile("^[0-9]*$");
        Matcher mh6 = pt6.matcher(value);
        boolean matchFound6 = mh6.matches();
        if (!(matchFound6)) {
            JOptionPane.showMessageDialog(null, "Enter the Numbers only");
            zipCodeJTextField5.setText("");
            zipCodeJTextField5.requestFocus();
        }else{
            if(value.length()!=5)
            { JOptionPane.showMessageDialog(null, "Enter 5 digit Zipcode", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
                zipCodeJTextField5.setText("");
                zipCodeJTextField5.requestFocus();
            }
        }
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_zipCodeJTextField5FocusLost

    private void usernameTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTextField1FocusLost
        String value = usernameTextField1.getText();
        if (value.equals("")) {
        } else {
        Pattern pt6 = Pattern.compile("^[a-zA-Z]*$");
        Matcher mh6 = pt6.matcher(value);
        boolean matchFound6 = mh6.matches();
        if (!(matchFound6)) {
            JOptionPane.showMessageDialog(null, "Enter the Characters only");
            usernameTextField1.setText("");
            usernameTextField1.requestFocus();
        }
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextField1FocusLost

    private void networkJComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkJComboBox1ActionPerformed
        createPersonJButton1.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_networkJComboBox1ActionPerformed

    private void countryJTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_countryJTextField1FocusLost
         String value = countryJTextField1.getText();
        if (value.equals("")) {
        } else {
        Pattern pt6 = Pattern.compile("^[a-zA-Z]*$");
        Matcher mh6 = pt6.matcher(value);
        boolean matchFound6 = mh6.matches();
        if (!(matchFound6)) {
            JOptionPane.showMessageDialog(null, "Enter the Characters only");
            countryJTextField1.setText("");
            countryJTextField1.requestFocus();
        }
    } // TODO add your handling code here:
    }//GEN-LAST:event_countryJTextField1FocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton1;
    private javax.swing.JTextField cityJTextField3;
    private javax.swing.JPasswordField confirmjPasswordField2;
    private javax.swing.JTextField countryJTextField1;
    private javax.swing.JButton createPersonJButton1;
    private javax.swing.JComboBox dayJComboBox1;
    private javax.swing.JLabel dobJLabel12;
    private javax.swing.JLabel firstNameJLabel10;
    private javax.swing.JTextField firstNameJTextField9;
    private javax.swing.JComboBox genderJComboBox1;
    private javax.swing.JLabel imageJLabel2;
    private javax.swing.JComboBox interestsJComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jcityJLabel3;
    private javax.swing.JLabel lastNameJLabel9;
    private javax.swing.JTextField lastNameJTextField10;
    private javax.swing.JComboBox monthJComboBox2;
    private javax.swing.JComboBox networkJComboBox1;
    private javax.swing.JTextField personIDJTextField14;
    private javax.swing.JLabel ssnJLabel14;
    private javax.swing.JLabel stateJLabel4;
    private javax.swing.JTextField stateJTextField4;
    private javax.swing.JLabel streetAddress1JLabel1;
    private javax.swing.JTextField streetAddress1JTextField1;
    private javax.swing.JLabel streetAddress2JLabel2;
    private javax.swing.JTextField streetAddress2JTextField2;
    private javax.swing.JTextField usernameTextField1;
    private javax.swing.JTextField yearsJTextField2;
    private javax.swing.JLabel zipCodeJLabel5;
    private javax.swing.JLabel zipCodeJLabel6;
    private javax.swing.JTextField zipCodeJTextField5;
    // End of variables declaration//GEN-END:variables
}
