/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.User;

import Interface.PublisherEnterprise.AdvertismentPages.AmazonWebPageJPanel;
import Interface.PublisherEnterprise.AdvertismentPages.FacebookWebPageJPanel;
import System.Enterprise.Enterprise;
import System.Enterprise.Publisher;
import System.Network.Network;
import System.UserAccount.EndUserUserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author SURAJ
 */
public class UserWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EndUserUserAccount userAccount;
    private Network network;
    private String name;
    private Publisher publisher;
    /**
     * Creates new form UserWorkAreaJPanel
     */
    public UserWorkAreaJPanel(JPanel userProcessContainer, Network network, EndUserUserAccount ua) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.userAccount=ua;
        this.network= network;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        page1Pub2JButton1 = new javax.swing.JButton();
        page1Pub1JButton3 = new javax.swing.JButton();
        imageJLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Browse Pages");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 330, 60));

        page1Pub2JButton1.setText("Facebook");
        page1Pub2JButton1.setToolTipText("Go to facebook.com");
        page1Pub2JButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        page1Pub2JButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        page1Pub2JButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                page1Pub2JButton1ActionPerformed(evt);
            }
        });
        add(page1Pub2JButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 210, 50));

        page1Pub1JButton3.setText("Amazon");
        page1Pub1JButton3.setToolTipText("Go to Amazon.com");
        page1Pub1JButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        page1Pub1JButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        page1Pub1JButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                page1Pub1JButton3ActionPerformed(evt);
            }
        });
        add(page1Pub1JButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 210, 50));

        imageJLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        imageJLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Organization Background.jpg"))); // NOI18N
        add(imageJLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 690));
    }// </editor-fold>//GEN-END:initComponents

    private void page1Pub1JButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_page1Pub1JButton3ActionPerformed

        name= "Amazon";
        for(Enterprise enterprise: network.getEnterpriseList())
         if(enterprise instanceof Publisher)
           if(enterprise.getName().equalsIgnoreCase(name)) 
             publisher= (Publisher) enterprise;
        if(publisher!=null){
        AmazonWebPageJPanel amazonWebPageJPanel= new AmazonWebPageJPanel(userProcessContainer,network, publisher, userAccount);
        userProcessContainer.add("AmazonWebPageJPanel", amazonWebPageJPanel);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_page1Pub1JButton3ActionPerformed

    private void page1Pub2JButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_page1Pub2JButton1ActionPerformed

        name= "Facebook";
        for(Enterprise enterprise: network.getEnterpriseList())
         if(enterprise instanceof Publisher)
           if(enterprise.getName().equalsIgnoreCase(name)) 
             publisher= (Publisher) enterprise;
        if(publisher!=null){
        FacebookWebPageJPanel facebookWebPageJPanel= new FacebookWebPageJPanel(userProcessContainer, network, publisher, userAccount);
        userProcessContainer.add("FacebookWebPageJPanel", facebookWebPageJPanel);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_page1Pub2JButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageJLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton page1Pub1JButton3;
    private javax.swing.JButton page1Pub2JButton1;
    // End of variables declaration//GEN-END:variables
}
