/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.AdvertiserEnterprise.SalesOrganization;

import System.AdSolution.Solution;
import System.Enterprise.Advertiser;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SURAJ
 */
public class ManageAdSolutionsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Advertiser advertiser;
    /**
     * Creates new form ManageAdSolutionsJPanel
     */
    public ManageAdSolutionsJPanel(JPanel userProcessContainer, Advertiser advertiser) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.advertiser= advertiser;
        populateAdSolutionTable();
    }

    private void populateAdSolutionTable()
    {
        DefaultTableModel model = (DefaultTableModel) adSolutionJTable1.getModel();
        model.setRowCount(0);
        
        for(Solution solution: advertiser.getSolutionCatalog().getSolutionList()){
            Object[] row = new Object[8];
            row[0]= solution;
            row[1]= solution.getAd().getAdID();
            row[2]= solution.getMinpageHit()+"-"+solution.getMaxPageHit();
            row[3]= solution.getAdPositon();
            row[4]= solution.getMinUserClicks()+"-"+solution.getMaxUserClicks();
            row[5]= solution.getGender();
            row[6]= solution.getMinAge()+"-"+solution.getMaxAge();
            row[7]= solution.getBidRate();
            model.addRow(row);
         }   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adSolutionJTable1 = new javax.swing.JTable();
        backJButton1 = new javax.swing.JButton();
        addAdSolutionJButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        refreshButton3 = new javax.swing.JButton();
        deleteAdvertismentsJButton1 = new javax.swing.JButton();
        viewDetailsJKButton2 = new javax.swing.JButton();
        imageJLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Manage Icon.png"))); // NOI18N
        jLabel1.setText("Manage Ad Solutions");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 420, 60));

        adSolutionJTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Solution ID", "Advertisment ID", "Page Hit Rate(Range)", "Ad Space Position", "User Clicks(Range)", "Gender", "Age Range", "Bid Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        adSolutionJTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adSolutionJTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(adSolutionJTable1);
        adSolutionJTable1.getColumnModel().getColumn(0).setPreferredWidth(13);
        adSolutionJTable1.getColumnModel().getColumn(5).setPreferredWidth(20);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 970, 390));

        backJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backbutton.png"))); // NOI18N
        backJButton1.setText("Back");
        backJButton1.setToolTipText("Back");
        backJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });
        add(backJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, 100, -1));

        addAdSolutionJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/addIcon.gif"))); // NOI18N
        addAdSolutionJButton1.setText(" Add");
        addAdSolutionJButton1.setToolTipText("Create Advertisment Solutions");
        addAdSolutionJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addAdSolutionJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAdSolutionJButton1ActionPerformed(evt);
            }
        });
        add(addAdSolutionJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 120, 30));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel10.setText("Create a Solution :");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 170, 30));

        refreshButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset-icon.png"))); // NOI18N
        refreshButton3.setText("Refresh");
        refreshButton3.setToolTipText("Refresh");
        refreshButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refreshButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButton3ActionPerformed(evt);
            }
        });
        add(refreshButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 80, 120, 30));

        deleteAdvertismentsJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete_icon.png"))); // NOI18N
        deleteAdvertismentsJButton1.setText("Delete");
        deleteAdvertismentsJButton1.setToolTipText("Delete Advertisment");
        deleteAdvertismentsJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteAdvertismentsJButton1.setEnabled(false);
        deleteAdvertismentsJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAdvertismentsJButton1ActionPerformed(evt);
            }
        });
        add(deleteAdvertismentsJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 560, 150, 40));

        viewDetailsJKButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon small.gif"))); // NOI18N
        viewDetailsJKButton2.setText("View Details");
        viewDetailsJKButton2.setToolTipText("View AdSolution Details");
        viewDetailsJKButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewDetailsJKButton2.setEnabled(false);
        viewDetailsJKButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsJKButton2ActionPerformed(evt);
            }
        });
        add(viewDetailsJKButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 520, 150, 40));

        imageJLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        imageJLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Advertiser BackGround.jpg"))); // NOI18N
        add(imageJLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        userProcessContainer.remove(this);
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_backJButton1ActionPerformed

    private void addAdSolutionJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAdSolutionJButton1ActionPerformed

        CreateAdSolutionJPanel createAdSolutionJPanel = new CreateAdSolutionJPanel(userProcessContainer, advertiser);
        userProcessContainer.add("CreateAdSolutionJPanel", createAdSolutionJPanel);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_addAdSolutionJButton1ActionPerformed

    private void refreshButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButton3ActionPerformed
        populateAdSolutionTable();
        viewDetailsJKButton2.setEnabled(false);
        deleteAdvertismentsJButton1.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshButton3ActionPerformed

    private void deleteAdvertismentsJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAdvertismentsJButton1ActionPerformed

        int selectedRow= adSolutionJTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row","Invalid Action", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Solution solution=   (Solution) adSolutionJTable1.getValueAt(selectedRow, 0);

        int value= JOptionPane.showConfirmDialog(null, "Are you sure to delete "+ solution.getSolutionID()+" ?", "Delete Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if(value == JOptionPane.YES_OPTION)
        {
            advertiser.getSolutionCatalog().getSolutionList().remove(solution);
            populateAdSolutionTable();
        }
        deleteAdvertismentsJButton1.setEnabled(false);
        viewDetailsJKButton2.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteAdvertismentsJButton1ActionPerformed

    private void viewDetailsJKButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsJKButton2ActionPerformed

        int selectedRow= adSolutionJTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row","Invalid Action", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Solution solution=   (Solution) adSolutionJTable1.getValueAt(selectedRow, 0);
        ViewSolutionDetailsJPanel viewSolutionDetailsJPanel= new ViewSolutionDetailsJPanel(userProcessContainer,advertiser, solution);
        userProcessContainer.add("ViewSolutionDetailsJPanel", viewSolutionDetailsJPanel);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_viewDetailsJKButton2ActionPerformed

    private void adSolutionJTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adSolutionJTable1MouseClicked
        int selectedRow= adSolutionJTable1.getSelectedRow();
        if (selectedRow < 0) return;
        Solution solution= (Solution) adSolutionJTable1.getValueAt(selectedRow, 0);
        if(solution!=null){
            viewDetailsJKButton2.setEnabled(true);
            deleteAdvertismentsJButton1.setEnabled(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_adSolutionJTable1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable adSolutionJTable1;
    private javax.swing.JButton addAdSolutionJButton1;
    private javax.swing.JButton backJButton1;
    private javax.swing.JButton deleteAdvertismentsJButton1;
    private javax.swing.JLabel imageJLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshButton3;
    private javax.swing.JButton viewDetailsJKButton2;
    // End of variables declaration//GEN-END:variables
}
