/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.AdvertiserEnterprise.SalesOrganization;

import System.AdSolution.Solution;
import System.Enterprise.Advertiser;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author SURAJ
 */
public class UpdateAdSolutionJPanel1 extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Solution solution;
    private Advertiser advertiser;
    /**
     * Creates new form CreateAdSolutionJPanel
     */
    public UpdateAdSolutionJPanel1(JPanel userProcessContainer, Advertiser advertiser, Solution solution) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.solution= solution;
        this.advertiser=advertiser;
        populateFields();
    }
   
    private void populateFields()
    {
        minPageRankJSpinner2.setValue(solution.getMinpageHit());
        maxPageRankJSpinner3.setValue(solution.getMaxPageHit());
        minUserClicksJSpinner4.setValue(solution.getMinUserClicks());
        maxUserClicksJSpinner5.setValue(solution.getMaxUserClicks());
        minAgeJSpinner1.setValue(solution.getMinAge());
        maxAgeJSpinner2.setValue(solution.getMaxAge());
        bidRateJTextField2.setText(String.valueOf(solution.getBidRate()));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        minPageRankJSpinner2 = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        maxPageRankJSpinner3 = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        adSpacePositionComboBox1 = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        minUserClicksJSpinner4 = new javax.swing.JSpinner();
        jLabel23 = new javax.swing.JLabel();
        maxUserClicksJSpinner5 = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        genderJComboBox2 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        minAgeJSpinner1 = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        maxAgeJSpinner2 = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        bidRateJTextField2 = new javax.swing.JTextField();
        backJButton1 = new javax.swing.JButton();
        saveJButton2 = new javax.swing.JButton();
        imageJLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update-icon.png"))); // NOI18N
        jLabel1.setText("Update Advertisment Solutions");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 420, 60));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update Solution", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Apple Braille", 1, 14))); // NOI18N
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(6, 2, 0, 4));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Page Rating :");
        jPanel1.add(jLabel14);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("From :");
        jPanel5.add(jLabel15);

        minPageRankJSpinner2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 9, 1));
        minPageRankJSpinner2.setPreferredSize(new java.awt.Dimension(60, 28));
        jPanel5.add(minPageRankJSpinner2);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("To :");
        jPanel5.add(jLabel16);

        maxPageRankJSpinner3.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        maxPageRankJSpinner3.setPreferredSize(new java.awt.Dimension(60, 28));
        jPanel5.add(maxPageRankJSpinner3);

        jPanel1.add(jPanel5);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("AdSpace Positon :");
        jPanel1.add(jLabel11);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        adSpacePositionComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Top", "Bottom" }));
        jPanel4.add(adSpacePositionComboBox1);

        jPanel1.add(jPanel4);

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("User Clicks :");
        jPanel1.add(jLabel21);

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("From :");
        jPanel7.add(jLabel22);

        minUserClicksJSpinner4.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        minUserClicksJSpinner4.setPreferredSize(new java.awt.Dimension(75, 28));
        jPanel7.add(minUserClicksJSpinner4);

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("To :");
        jPanel7.add(jLabel23);

        maxUserClicksJSpinner5.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        maxUserClicksJSpinner5.setPreferredSize(new java.awt.Dimension(75, 28));
        jPanel7.add(maxUserClicksJSpinner5);

        jPanel1.add(jPanel7);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Gender :");
        jPanel1.add(jLabel9);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        genderJComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Male", "Female" }));
        genderJComboBox2.setPreferredSize(new java.awt.Dimension(101, 27));
        jPanel2.add(genderJComboBox2);

        jPanel1.add(jPanel2);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Age Group :");
        jPanel1.add(jLabel12);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("From :");
        jPanel3.add(jLabel13);

        minAgeJSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));
        minAgeJSpinner1.setPreferredSize(new java.awt.Dimension(60, 28));
        jPanel3.add(minAgeJSpinner1);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("To :");
        jPanel3.add(jLabel8);

        maxAgeJSpinner2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        maxAgeJSpinner2.setPreferredSize(new java.awt.Dimension(60, 28));
        jPanel3.add(maxAgeJSpinner2);

        jPanel1.add(jPanel3);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Bid Rate (in USD) :");
        jPanel1.add(jLabel7);

        bidRateJTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bidRateJTextField2FocusLost(evt);
            }
        });
        jPanel1.add(bidRateJTextField2);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 620, 270));

        backJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backbutton.png"))); // NOI18N
        backJButton1.setText("Back");
        backJButton1.setToolTipText("Back");
        backJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });
        add(backJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 90, -1));

        saveJButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save_icon.gif"))); // NOI18N
        saveJButton2.setText("Save");
        saveJButton2.setToolTipText("Save Details");
        saveJButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJButton2ActionPerformed(evt);
            }
        });
        add(saveJButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 446, 100, 30));

        imageJLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        imageJLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Advertiser BackGround.jpg"))); // NOI18N
        add(imageJLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        userProcessContainer.remove(this);
         ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_backJButton1ActionPerformed

    private void saveJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJButton2ActionPerformed

      
        String position= (String) adSpacePositionComboBox1.getSelectedItem();
        String gender= (String) genderJComboBox2.getSelectedItem();
        if(gender.isEmpty()|| position.isEmpty()||bidRateJTextField2.getText().isEmpty())
        {
          JOptionPane.showMessageDialog(null, "One or more fields are empty", "Error", JOptionPane.ERROR_MESSAGE);
          return;
        }
        int minPageHit = (int) minPageRankJSpinner2.getValue();
        int maxPageHit = (int) maxPageRankJSpinner3.getValue();
        if(minPageHit>=maxPageHit)
        {
            JOptionPane.showMessageDialog(null, "Maximum Page Ranking must be \ngreater then Minimum value", "Invalid Entry", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int minUserClicks = (int) minUserClicksJSpinner4.getValue();
        int maxUserClicks = (int) maxUserClicksJSpinner5.getValue();
        if(minUserClicks>=maxUserClicks)
        {
            JOptionPane.showMessageDialog(null, "Maximum User clicks must be \nmore then Minimum value", "Invalid Entry", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int minAge = (int) minAgeJSpinner1.getValue();
        int maxAge = (int) maxAgeJSpinner2.getValue();
        if(minAge>=maxAge)
        {
            JOptionPane.showMessageDialog(null, "Maximum age must be greater \nthen Minimum age value", "Invalid Entry", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(bidRateJTextField2.getText().contains("-")) return;
        double bidRate;
        try {
            bidRate = Double.parseDouble(bidRateJTextField2.getText());
        } catch (Exception e) {
           return;
        }
        Boolean exists= advertiser.getSolutionCatalog().checkForSolution(solution.getAd(), position, maxAge, minAge, bidRate, gender,
                                                                maxPageHit, minPageHit, maxUserClicks, minUserClicks);       
        if(exists) {
            JOptionPane.showMessageDialog(null, "Solution already Exists \nPlease enter different parameters", "Solution Duplication", JOptionPane.ERROR_MESSAGE);
            return;
        }
        solution.setAdPositon(position);
        solution.setMinpageHit(minPageHit);
        solution.setMaxPageHit(maxPageHit);
        solution.setMinUserClicks(minUserClicks);
        solution.setMaxUserClicks(maxUserClicks);
        solution.setMaxAge(maxAge);
        solution.setMinAge(minAge);
        solution.setGender(gender);
        solution.setBidRate(bidRate);
        JOptionPane.showMessageDialog(null, "Ad Solution Updated Successfully","", JOptionPane.INFORMATION_MESSAGE);
        userProcessContainer.remove(this);
         ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_saveJButton2ActionPerformed

    private void bidRateJTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bidRateJTextField2FocusLost

        String value = bidRateJTextField2.getText();
        if (value.equals("")) {
        } else {
        Pattern pt6 = Pattern.compile("^[0-9\\.]*$");
        Matcher mh6 = pt6.matcher(value);
        boolean matchFound6 = mh6.matches();
         if (!(matchFound6)) {
            JOptionPane.showMessageDialog(null, "Enter a valid amount value");
            bidRateJTextField2.setText("");
            bidRateJTextField2.requestFocus();
          }
       }
    }//GEN-LAST:event_bidRateJTextField2FocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox adSpacePositionComboBox1;
    private javax.swing.JButton backJButton1;
    private javax.swing.JTextField bidRateJTextField2;
    private javax.swing.JComboBox genderJComboBox2;
    private javax.swing.JLabel imageJLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSpinner maxAgeJSpinner2;
    private javax.swing.JSpinner maxPageRankJSpinner3;
    private javax.swing.JSpinner maxUserClicksJSpinner5;
    private javax.swing.JSpinner minAgeJSpinner1;
    private javax.swing.JSpinner minPageRankJSpinner2;
    private javax.swing.JSpinner minUserClicksJSpinner4;
    private javax.swing.JButton saveJButton2;
    // End of variables declaration//GEN-END:variables
}
