/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.AdvertiserEnterprise.SalesOrganization;

import System.AdSolution.Solution;
import System.Enterprise.Advertiser;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author SURAJ
 */
public class ViewSolutionDetailsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Solution solution;
     private Advertiser advertiser;
    /**
     * Creates new form ViewSolutionDetailsJPanel
     */
    public ViewSolutionDetailsJPanel(JPanel userProcessContainer, Advertiser advertiser,Solution solution) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.solution= solution;
         this.advertiser=advertiser;
        populateFields();
    }

    private void populateFields()
    {
        solutionIDjLabel10.setText(String.valueOf(solution.getSolutionID()));
        adIDLabel15.setText(String.valueOf(solution.getAd().getAdID()));
        productTyoeLabel17.setText(solution.getAd().getProductType());
        
        pageRankingJLabel2.setText(String.valueOf(solution.getMinpageHit()+"-"+ solution.getMaxPageHit()));
        adPositionJLabel3.setText(solution.getAdPositon());
        
        userClicksLabel7.setText(String.valueOf(solution.getMinUserClicks()+"-"+ solution.getMaxUserClicks()));
        genderJLabel4.setText(solution.getGender());
        ageGroupJLabel5.setText(String.valueOf(solution.getMinAge()+"-"+solution.getMaxAge()));
        bidRateLabel6.setText(String.valueOf(solution.getBidRate()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton1 = new javax.swing.JButton();
        updateJButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pageRankingJLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        adPositionJLabel3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        userClicksLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        genderJLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ageGroupJLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bidRateLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        solutionIDjLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        adIDLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        productTyoeLabel17 = new javax.swing.JLabel();
        refreshButton3 = new javax.swing.JButton();
        imageJLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backbutton.png"))); // NOI18N
        backJButton1.setText("Back");
        backJButton1.setToolTipText("Back");
        backJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });
        add(backJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 590, 90, -1));

        updateJButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset-icon.png"))); // NOI18N
        updateJButton2.setText("Update");
        updateJButton2.setToolTipText("Update Solution");
        updateJButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateJButton2ActionPerformed(evt);
            }
        });
        add(updateJButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 590, 100, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Other Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Apple Braille", 1, 14))); // NOI18N
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(8, 2, 0, 4));

        jLabel2.setText("   Publisher Page Details :");
        jPanel1.add(jLabel2);
        jPanel1.add(jLabel5);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Page Rating :");
        jPanel1.add(jLabel14);
        jPanel1.add(pageRankingJLabel2);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("AdSpace Positon :");
        jPanel1.add(jLabel11);
        jPanel1.add(adPositionJLabel3);

        jLabel3.setText("   Person Details :");
        jPanel1.add(jLabel3);
        jPanel1.add(jLabel4);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("User Clicks :");
        jPanel1.add(jLabel10);
        jPanel1.add(userClicksLabel7);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Gender :");
        jPanel1.add(jLabel9);
        jPanel1.add(genderJLabel4);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Age Group :");
        jPanel1.add(jLabel12);
        jPanel1.add(ageGroupJLabel5);

        jLabel7.setText("   Bid Rate (in USD) :");
        jPanel1.add(jLabel7);
        jPanel1.add(bidRateLabel6);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 620, 280));

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/View_icon.png"))); // NOI18N
        jLabel1.setText("View Advertisment Solutions");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 420, 60));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Solution Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Apple Braille", 1, 14))); // NOI18N
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(3, 2, 0, 4));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Solution ID :");
        jPanel2.add(jLabel8);
        jPanel2.add(solutionIDjLabel10);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Advertisment ID :");
        jPanel2.add(jLabel13);
        jPanel2.add(adIDLabel15);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText(" Product Type :");
        jPanel2.add(jLabel16);
        jPanel2.add(productTyoeLabel17);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 620, 140));

        refreshButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset-icon.png"))); // NOI18N
        refreshButton3.setText("Refresh");
        refreshButton3.setToolTipText("Refresh Fields");
        refreshButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refreshButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButton3ActionPerformed(evt);
            }
        });
        add(refreshButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 110, 30));

        imageJLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        imageJLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Advertiser BackGround.jpg"))); // NOI18N
        add(imageJLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_backJButton1ActionPerformed

    private void updateJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateJButton2ActionPerformed

        UpdateAdSolutionJPanel1 updateAdSolutionJPanel1= new UpdateAdSolutionJPanel1(userProcessContainer, advertiser,solution);
        userProcessContainer.add("UpdateAdSolutionJPanel1", updateAdSolutionJPanel1);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_updateJButton2ActionPerformed

    private void refreshButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButton3ActionPerformed
       populateFields();
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adIDLabel15;
    private javax.swing.JLabel adPositionJLabel3;
    private javax.swing.JLabel ageGroupJLabel5;
    private javax.swing.JButton backJButton1;
    private javax.swing.JLabel bidRateLabel6;
    private javax.swing.JLabel genderJLabel4;
    private javax.swing.JLabel imageJLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel pageRankingJLabel2;
    private javax.swing.JLabel productTyoeLabel17;
    private javax.swing.JButton refreshButton3;
    private javax.swing.JLabel solutionIDjLabel10;
    private javax.swing.JButton updateJButton2;
    private javax.swing.JLabel userClicksLabel7;
    // End of variables declaration//GEN-END:variables
}
