/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.PublisherEnterprise;

import Interface.Organizations.ManageOrganizationEmployeeJPanel;
import Interface.Organizations.ManageOrganizationJPanel;
import Interface.Organizations.ManageOrganizationPersonJPanel;
import Interface.Organizations.ManageOrganizationUserAccountJPanel;
import System.EcoSystem;
import java.awt.CardLayout;
import javax.swing.JPanel;
import System.Enterprise.Publisher;
import System.Network.Network;
import System.Person.Person;
import System.UserAccount.EmployeeUserAccount;

/**
 *
 * @author SURAJ
 */
public class PublisherAdminWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Publisher publisher;
    private Network network;
    private EcoSystem system;
    private Person person;
    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public PublisherAdminWorkAreaJPanel(JPanel userProcessContainer, EcoSystem system,Publisher publisher, Network n, EmployeeUserAccount userAccount) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.publisher= publisher;
        this.network= n;
        this.system= system;
        for(Person p: publisher.getPersonDirectory().getPersonlist())
        if(p.getPersonID()==(userAccount.getEmployee().getPerson().getPersonID()))
        {
            person=p;
            nameJLabel3.setText(p.getFirstName()+" "+p.getLastName());
        }
        enterpriseNameJLabel2.setText(publisher.getName());
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameJLabel3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        viewWorkQueueJButton2 = new javax.swing.JButton();
        manageOrgJButton1 = new javax.swing.JButton();
        manageUAJButton2 = new javax.swing.JButton();
        manageEmployeeJButton3 = new javax.swing.JButton();
        managePersonJButton1 = new javax.swing.JButton();
        enterpriseNameJLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        imageJLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Publisher Administrator Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 420, 60));

        nameJLabel3.setFont(new java.awt.Font("Arial Unicode MS", 1, 16)); // NOI18N
        add(nameJLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 170, 30));

        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 1, 16)); // NOI18N
        jLabel3.setText("Name :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 60, 30));

        viewWorkQueueJButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/work request icon.png"))); // NOI18N
        viewWorkQueueJButton2.setText("View Work Requests");
        viewWorkQueueJButton2.setToolTipText("Manage Work Requests");
        viewWorkQueueJButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewWorkQueueJButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewWorkQueueJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewWorkQueueJButton2ActionPerformed(evt);
            }
        });
        add(viewWorkQueueJButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 570, 240, 50));

        manageOrgJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Manage Icon.png"))); // NOI18N
        manageOrgJButton1.setText("Manage Organization");
        manageOrgJButton1.setToolTipText("Manage Organization");
        manageOrgJButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageOrgJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageOrgJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrgJButton1ActionPerformed(evt);
            }
        });
        add(manageOrgJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 240, 50));

        manageUAJButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Manage User Accounts.png"))); // NOI18N
        manageUAJButton2.setText("Manage User Account");
        manageUAJButton2.setToolTipText("Manage User Account");
        manageUAJButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageUAJButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageUAJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUAJButton2ActionPerformed(evt);
            }
        });
        add(manageUAJButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, 240, 50));

        manageEmployeeJButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Manage Employee.png"))); // NOI18N
        manageEmployeeJButton3.setText("Manage Employee");
        manageEmployeeJButton3.setToolTipText("Manage Employee Profiles");
        manageEmployeeJButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageEmployeeJButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageEmployeeJButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeJButton3ActionPerformed(evt);
            }
        });
        add(manageEmployeeJButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 240, 50));

        managePersonJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/manage_person.png"))); // NOI18N
        managePersonJButton1.setText("Manage Person");
        managePersonJButton1.setToolTipText("Manage Person Profiles");
        managePersonJButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        managePersonJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        managePersonJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePersonJButton1ActionPerformed(evt);
            }
        });
        add(managePersonJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 240, 50));

        enterpriseNameJLabel2.setFont(new java.awt.Font("Arial Unicode MS", 1, 20)); // NOI18N
        add(enterpriseNameJLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 200, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Manage Organization.jpg"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 800, 170));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Manage Person Small.png"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 800, 220));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Request Icon.jpg"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, 800, 120));

        imageJLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        imageJLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Publisher Back Ground.jpeg"))); // NOI18N
        add(imageJLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 690));
    }// </editor-fold>//GEN-END:initComponents

    private void viewWorkQueueJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewWorkQueueJButton2ActionPerformed

        ManageWorkRequestsJPanel manageWorkRequestsJPanel= new ManageWorkRequestsJPanel(userProcessContainer, publisher, network);
        userProcessContainer.add("ManageWorkRequestsJPanel", manageWorkRequestsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_viewWorkQueueJButton2ActionPerformed

    private void manageOrgJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrgJButton1ActionPerformed

        ManageOrganizationJPanel manageOrganizationJPanel= new ManageOrganizationJPanel(userProcessContainer, publisher, person);
        userProcessContainer.add("ManageOrganizationJPanel", manageOrganizationJPanel);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_manageOrgJButton1ActionPerformed

    private void manageUAJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUAJButton2ActionPerformed

        ManageOrganizationUserAccountJPanel manageOrganizationUserAccountJPanel= new ManageOrganizationUserAccountJPanel(userProcessContainer, system, publisher, person);
        userProcessContainer.add("ManageOrganizationUserAccountJPanel", manageOrganizationUserAccountJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_manageUAJButton2ActionPerformed

    private void manageEmployeeJButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeJButton3ActionPerformed

        ManageOrganizationEmployeeJPanel manageEmployeeAdvOrganizationJPanel= new ManageOrganizationEmployeeJPanel(userProcessContainer, person, publisher );
        userProcessContainer.add("ManageEmployeeAdvOrganizationJPanel", manageEmployeeAdvOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_manageEmployeeJButton3ActionPerformed

    private void managePersonJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePersonJButton1ActionPerformed

        ManageOrganizationPersonJPanel managePersonAdvEnterpriseJPanel = new ManageOrganizationPersonJPanel(userProcessContainer, system, publisher, person);
        userProcessContainer.add("ManagePersonAdvEnterpriseJPanel", managePersonAdvEnterpriseJPanel);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_managePersonJButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseNameJLabel2;
    private javax.swing.JLabel imageJLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton manageEmployeeJButton3;
    private javax.swing.JButton manageOrgJButton1;
    private javax.swing.JButton managePersonJButton1;
    private javax.swing.JButton manageUAJButton2;
    private javax.swing.JLabel nameJLabel3;
    private javax.swing.JButton viewWorkQueueJButton2;
    // End of variables declaration//GEN-END:variables
}
