/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.AdExchangeEnterprise.MarketOrganization;

import System.Enterprise.AdExchange;
import System.Market.Market;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SURAJ
 */
public class ManageMarketJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private AdExchange exchange;
    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageMarketJPanel(JPanel userProcessContainer, AdExchange enterprise) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.exchange= enterprise;
         populateTable();
         populateComboBox();
    }

    private void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel) marketJTable1.getModel();
        model.setRowCount(0);
        
        for(Market market: exchange.getMarketDirectory().getMarketList()){
            Object[] object = new Object[1];
            object[0]= market;
            model.addRow(object);
         }
    }
    
    private void populateComboBox()
    {
        marketTypeJComboBox1.removeAllItems();
        marketTypeJComboBox1.addItem(Market.SPORTS);
        marketTypeJComboBox1.addItem(Market.ELECTRONICS);
        marketTypeJComboBox1.addItem(Market.CLOTHING);
        marketTypeJComboBox1.addItem(Market.HEALTHMARKET);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        marketJTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        addMarketJButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        deleteMarketJButton2 = new javax.swing.JButton();
        backJButton1 = new javax.swing.JButton();
        marketTypeJComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        imageJLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        marketJTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Market Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        marketJTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                marketJTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(marketJTable1);
        marketJTable1.getColumnModel().getColumn(0).setResizable(false);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 640, 170));

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Manage Icon.png"))); // NOI18N
        jLabel1.setText("Manage Markets");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 420, 60));

        addMarketJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/addIcon.gif"))); // NOI18N
        addMarketJButton1.setText("Add Market");
        addMarketJButton1.setToolTipText("Create Market");
        addMarketJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addMarketJButton1.setEnabled(false);
        addMarketJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMarketJButton1ActionPerformed(evt);
            }
        });
        add(addMarketJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, 150, 30));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel10.setText("Create Market Place:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 160, 30));

        deleteMarketJButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete_icon.png"))); // NOI18N
        deleteMarketJButton2.setText("Delete Market");
        deleteMarketJButton2.setToolTipText("Delete Market");
        deleteMarketJButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteMarketJButton2.setEnabled(false);
        deleteMarketJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMarketJButton2ActionPerformed(evt);
            }
        });
        add(deleteMarketJButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, 160, 30));

        backJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backbutton.png"))); // NOI18N
        backJButton1.setText("Back");
        backJButton1.setToolTipText("Back");
        backJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });
        add(backJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 80, -1));

        marketTypeJComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                marketTypeJComboBox1MouseClicked(evt);
            }
        });
        add(marketTypeJComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 150, 30));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("Select Market Type :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 140, 30));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel9.setText("Market List :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 130, 30));

        imageJLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        imageJLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AdExchange Background.jpg"))); // NOI18N
        add(imageJLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addMarketJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMarketJButton1ActionPerformed

        String marketType = (String) marketTypeJComboBox1.getSelectedItem();
        if(marketType == null)
        {
            JOptionPane.showMessageDialog(null, "Please select a Market","Invalid Action", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Boolean exists=  exchange.getMarketDirectory().checkMarketbyType(marketType);
        if(!exists)
        {
          Market market= exchange.getMarketDirectory().createAndAddMarket();
          market.setMarketType(marketType);
          populateTable();
          JOptionPane.showMessageDialog(null, "Market Place Created Successfully","", JOptionPane.INFORMATION_MESSAGE);
          addMarketJButton1.setEnabled(false);
        }else JOptionPane.showMessageDialog(null, "Market Already Exists in Exchange","Unable to add Market", JOptionPane.ERROR_MESSAGE);
        // TODO add your handling code here:
    }//GEN-LAST:event_addMarketJButton1ActionPerformed

    private void deleteMarketJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMarketJButton2ActionPerformed

        int selectedRow= marketJTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Row","Invalid Action", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Market market = (Market) marketJTable1.getValueAt(selectedRow, 0);

        int dialogButton = JOptionPane.YES_NO_OPTION;
        int response= JOptionPane.showConfirmDialog(null, "Are you sure to delete "+ market.getMarketType() +" ?", "Delete Confirmation", dialogButton, JOptionPane.WARNING_MESSAGE);
        if(response == JOptionPane.YES_OPTION)
        exchange.getMarketDirectory().getMarketList().remove(market);
        populateTable();

        // TODO add your handling code here:
    }//GEN-LAST:event_deleteMarketJButton2ActionPerformed

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed

        userProcessContainer.remove(this);
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_backJButton1ActionPerformed

    private void marketTypeJComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marketTypeJComboBox1MouseClicked
        addMarketJButton1.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_marketTypeJComboBox1MouseClicked

    private void marketJTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marketJTable1MouseClicked
        int selectedRow= marketJTable1.getSelectedRow();
        if (selectedRow < 0) return;
        Market market = (Market) marketJTable1.getValueAt(selectedRow, 0);
        if(market!=null) deleteMarketJButton2.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_marketJTable1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMarketJButton1;
    private javax.swing.JButton backJButton1;
    private javax.swing.JButton deleteMarketJButton2;
    private javax.swing.JLabel imageJLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable marketJTable1;
    private javax.swing.JComboBox marketTypeJComboBox1;
    // End of variables declaration//GEN-END:variables
}
