/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.AdvertiserEnterprise.MarketingOrganization;

import System.Advertisments.Advertisment;
import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author SURAJ
 */
public class ViewAdDetailsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Advertisment advertisment;
    /**
     * Creates new form ViewAdDetailsJPanel
     */
    public ViewAdDetailsJPanel(JPanel userProcessContainer,Advertisment advertisment) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.advertisment= advertisment;
        populateFields();
    }

    private void populateFields()
    {
        adIDLabel2.setText(String.valueOf(advertisment.getAdID()));
        productTypejLabel3.setText(advertisment.getProductType());
        String imagePath= advertisment.getAdImagePath();
         if (imagePath != null)
          {
           ImageIcon icon= new ImageIcon(imagePath);
           Image img = icon.getImage();
           Image newimg = img.getScaledInstance(500, 300,  java.awt.Image.SCALE_SMOOTH);  
           ImageIcon newIcon = new ImageIcon(newimg); 
           adImageLabel2.setIcon(newIcon);
          }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        adIDLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        productTypejLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        adImageLabel2 = new javax.swing.JLabel();
        backJButton1 = new javax.swing.JButton();
        imageJLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/View_icon.png"))); // NOI18N
        jLabel1.setText("Advertisment Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 420, 60));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "View Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Apple Braille", 1, 14))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(2, 2, 0, 4));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("    Advertisment ID :");
        jPanel1.add(jLabel5);
        jPanel1.add(adIDLabel2);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Product Type :");
        jPanel1.add(jLabel6);
        jPanel1.add(productTypejLabel3);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 450, 110));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("AD Image :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 80, 30));
        add(adImageLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 490, 290));

        backJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backbutton.png"))); // NOI18N
        backJButton1.setText("Back");
        backJButton1.setToolTipText("Back");
        backJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });
        add(backJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 600, 90, -1));

        imageJLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        imageJLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Advertiser BackGround.jpg"))); // NOI18N
        add(imageJLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_backJButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adIDLabel2;
    private javax.swing.JLabel adImageLabel2;
    private javax.swing.JButton backJButton1;
    private javax.swing.JLabel imageJLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel productTypejLabel3;
    // End of variables declaration//GEN-END:variables
}
