/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Interface.User.NewUserSignUpJPanel;
import System.Organization.Organization;
import System.UserAccount.UserAccount;
import System.Enterprise.Enterprise;
import System.Network.Network;
import System.DB4O.DB4OUtil;
import java.awt.CardLayout;
import javax.swing.JPanel;
import System.EcoSystem;
import javax.swing.JOptionPane;


/**
 *
 * @author SURAJ
 */
public class MainJFrame extends javax.swing.JFrame {

    private EcoSystem system;
    private DB4OUtil dB4OUtil;

    public MainJFrame() {
        initComponents();
        dB4OUtil = DB4OUtil.getInstance();
        system = dB4OUtil.retrieveSystem();
        MainBlankJPanel mainBlankJPanel= new MainBlankJPanel();
        userProcessContainer.add("MainBlankJPanel",mainBlankJPanel);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        userNameTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginJButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        newUserSignupButton1 = new javax.swing.JButton();
        logoutJButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        imageJLabel5 = new javax.swing.JLabel();
        userProcessContainer = new javax.swing.JPanel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(220);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userNameTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userNameTextField1MouseClicked(evt);
            }
        });
        jPanel1.add(userNameTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 110, -1));

        jLabel1.setFont(new java.awt.Font("Arial Hebrew", 1, 14)); // NOI18N
        jLabel1.setText("Click here for Sign-up :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 170, 30));

        jLabel2.setFont(new java.awt.Font("Arial Hebrew", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/key_icon.gif"))); // NOI18N
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 100, 30));

        loginJButton1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        loginJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login Button.png"))); // NOI18N
        loginJButton1.setText("Login");
        loginJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(loginJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 140, 50));
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 110, -1));

        jLabel3.setFont(new java.awt.Font("Arial Hebrew", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(1, 1, 120));
        jLabel3.setText("System Login:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, 30));

        newUserSignupButton1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        newUserSignupButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sign-up-icon.png"))); // NOI18N
        newUserSignupButton1.setText("SignUp");
        newUserSignupButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserSignupButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(newUserSignupButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 130, 50));

        logoutJButton1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        logoutJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logout.png"))); // NOI18N
        logoutJButton1.setText("Logout");
        logoutJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutJButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(logoutJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, 130, 50));

        jLabel5.setFont(new java.awt.Font("Arial Hebrew", 1, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/personal-information-icon.png"))); // NOI18N
        jLabel5.setText("Username");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 100, 30));

        jLabel6.setFont(new java.awt.Font("Arial Hebrew", 1, 14)); // NOI18N
        jLabel6.setText("New User ?");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 100, 30));

        imageJLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Network.jpg"))); // NOI18N
        jPanel1.add(imageJLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 720));

        jSplitPane1.setLeftComponent(jPanel1);

        userProcessContainer.setPreferredSize(new java.awt.Dimension(500, 500));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(userProcessContainer);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButton1ActionPerformed

       String username = userNameTextField1.getText();
       char[] charPassword = jPasswordField1.getPassword();
       String password = String.valueOf(charPassword);
       UserAccount userAccount1= system.getUserAccountDirectory().authenticateUser(username, password);
       if(userAccount1 != null) loginUser(userAccount1, null, null, null);
       else if(!enterpriseAndOrganizationUserCheck(username, password))
               JOptionPane.showMessageDialog(null, "Username or password is not correct","Invalid Entry",JOptionPane.ERROR_MESSAGE);
           
            // TODO add your handling code here:
    }//GEN-LAST:event_loginJButton1ActionPerformed

    private void newUserSignupButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserSignupButton1ActionPerformed

        NewUserSignUpJPanel newUserSignUpJPanel= new NewUserSignUpJPanel(userProcessContainer, system);
        userProcessContainer.add("NewUserSignUpJPanel", newUserSignUpJPanel);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_newUserSignupButton1ActionPerformed

    private void logoutJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutJButton1ActionPerformed

        dB4OUtil.storeSystem(system);
        userProcessContainer.removeAll();
        userNameTextField1.setText("");
        jPasswordField1.setText("");
        MainBlankJPanel mainBlankJPanel= new MainBlankJPanel();
        userProcessContainer.add("MainBlankJPanel",mainBlankJPanel);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
        JOptionPane.showMessageDialog(null, "Logged out");

        // TODO add your handling code here:
    }//GEN-LAST:event_logoutJButton1ActionPerformed

    private void userNameTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userNameTextField1MouseClicked
        MainBlankJPanel mainBlankJPanel= new MainBlankJPanel();
        userProcessContainer.add("MainBlankJPanel",mainBlankJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        userNameTextField1.setText("");
        jPasswordField1.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTextField1MouseClicked

    private Boolean enterpriseAndOrganizationUserCheck(String username, String password)
    {   
        for(Network n: system.getNetworkList()){
          if(n.getUserOrganization()!=null){
               UserAccount account= n.getUserOrganization().getUserAccountDirectory().authenticateUser(username, password);
            if(account!= null) {
                 loginUser(account, null, null, n);
                 return true;
            }}
           for(Enterprise e:n.getEnterpriseList()){
            UserAccount userAccount2= e.getUserAccountDirectory().authenticateUser(username, password);
             if(userAccount2 != null) {
                 loginUser(userAccount2, null, e, n);
                 return true;
             }else{
             for(Organization o: e.getOrganizationDirectory().getOrganizationList()){
              UserAccount userAccount3= o.getUserAccountDirectory().authenticateUser(username, password);
               if(userAccount3!= null) {
                 loginUser(userAccount3, o, e, n);
                 return true;
            }}}}}
       return false;
    }
    private void loginUser(UserAccount userAccount, Organization organization, Enterprise enterprise, Network network){
        JPanel workArea = userAccount.getRole().createWorkArea(userProcessContainer, system, network,
                                                    enterprise, organization, userAccount);
        userProcessContainer.add("WorkArea", workArea);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageJLabel5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton loginJButton1;
    private javax.swing.JButton logoutJButton1;
    private javax.swing.JButton newUserSignupButton1;
    private javax.swing.JTextField userNameTextField1;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
