/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
/**
 *
 * @author SURAJ
 */
public class MainBlankJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainBlankJPanel
     */
    public MainBlankJPanel() {
        initComponents();
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageJLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imageJLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        imageJLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Main Page backgroud.jpg"))); // NOI18N
        add(imageJLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 690));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageJLabel1;
    // End of variables declaration//GEN-END:variables
}
