/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.EcoSystemAdmin;

import System.Enterprise.AdExchange;
import System.Enterprise.Advertiser;
import System.Enterprise.Enterprise.Type;
import System.Enterprise.Publisher;
import System.Network.Network;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author SURAJ
 */
public class CreateEnterpriseJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Network network;
    /**
     * Creates new form CreateEnterpriseJPanel
     */
    public CreateEnterpriseJPanel(JPanel userProcessContainer, Network network) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.network=network;
        populateEnterpriseTypeComboBox();
    }

    private void populateEnterpriseTypeComboBox()
    {
       enterpriseTypeJComboBox1.removeAllItems();
       enterpriseTypeJComboBox1.addItem(Type.PUBLISHER.getValue());
       enterpriseTypeJComboBox1.addItem(Type.ADEXCHANGE.getValue());
       enterpriseTypeJComboBox1.addItem(Type.ADVERTISER.getValue());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        createEnterpriseJButton1 = new javax.swing.JButton();
        backJButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        namejTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        locationJTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        enterpriseTypeJComboBox1 = new javax.swing.JComboBox();
        imageJLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/create icon.png"))); // NOI18N
        jLabel1.setText("Create Enterprise");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 330, 60));

        createEnterpriseJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save_icon.gif"))); // NOI18N
        createEnterpriseJButton1.setText("Create");
        createEnterpriseJButton1.setToolTipText("Create Enterprise");
        createEnterpriseJButton1.setEnabled(false);
        createEnterpriseJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEnterpriseJButton1ActionPerformed(evt);
            }
        });
        add(createEnterpriseJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, 100, 30));

        backJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backbutton.png"))); // NOI18N
        backJButton1.setText("Back");
        backJButton1.setToolTipText("Back");
        backJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });
        add(backJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 90, -1));
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, -40, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Create Enterprise", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Apple Braille", 1, 14))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(3, 2, 0, 4));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Name :");
        jPanel2.add(jLabel5);

        namejTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                namejTextField1FocusLost(evt);
            }
        });
        jPanel2.add(namejTextField1);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Location:");
        jPanel2.add(jLabel4);

        locationJTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                locationJTextField1FocusLost(evt);
            }
        });
        jPanel2.add(locationJTextField1);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Type :");
        jPanel2.add(jLabel3);

        enterpriseTypeJComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enterpriseTypeJComboBox1MouseClicked(evt);
            }
        });
        jPanel2.add(enterpriseTypeJComboBox1);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 530, 150));

        imageJLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        imageJLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/110637_SystemManagebackgroundPanel.jpg"))); // NOI18N
        add(imageJLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void createEnterpriseJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEnterpriseJButton1ActionPerformed
        
        String name= namejTextField1.getText();
        String location= locationJTextField1.getText();
        if(name.isEmpty()||location.isEmpty()){
            JOptionPane.showMessageDialog(null, "One or more fields are Empty","", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        Boolean exists= network.checkEnterpriseNameAndLocation(name, location);
        if(!exists)
        {
            String value = (String) enterpriseTypeJComboBox1.getSelectedItem();
         if(value.equals(Type.PUBLISHER.getValue())){
             Publisher publisher = new Publisher(name);
             publisher.setLocation(location);
             network.getEnterpriseList().add(publisher);
          }
         else if(value.equals(Type.ADEXCHANGE.getValue())){
             AdExchange adExchange= new AdExchange(name);
             adExchange.setLocation(location);
             network.getEnterpriseList().add(adExchange);
         }
         else if(value.equals(Type.ADVERTISER.getValue())){
             Advertiser advertiser= new Advertiser(name);
             advertiser.setLocation(location);
             network.getEnterpriseList().add(advertiser);
         }
         JOptionPane.showMessageDialog(null, "Enterprise Created Successfully","", JOptionPane.INFORMATION_MESSAGE);
         userProcessContainer.remove(this);
         ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
        }
        else  {
            JOptionPane.showMessageDialog(null, "Please enter different Enterprise Name and Location","Information Duplication", JOptionPane.ERROR_MESSAGE);
            namejTextField1.setBackground(Color.yellow);
            locationJTextField1.setBackground(Color.yellow);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_createEnterpriseJButton1ActionPerformed

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed

        userProcessContainer.remove(this);
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_backJButton1ActionPerformed

    private void enterpriseTypeJComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterpriseTypeJComboBox1MouseClicked

        createEnterpriseJButton1.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_enterpriseTypeJComboBox1MouseClicked

    private void namejTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namejTextField1FocusLost
        String value = namejTextField1.getText();
        if (value.equals("")) {
        } else {
        Pattern pt6 = Pattern.compile("^[a-zA-Z\\ ]*$");
        Matcher mh6 = pt6.matcher(value);
        boolean matchFound6 = mh6.matches();
        if (!(matchFound6)) {
            JOptionPane.showMessageDialog(null, "Enter the Characters only");
            namejTextField1.setText("");
            namejTextField1.requestFocus();
        }
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_namejTextField1FocusLost

    private void locationJTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_locationJTextField1FocusLost
        String value = locationJTextField1.getText();
        if (value.equals("")) {
        } else {
        Pattern pt6 = Pattern.compile("^[a-zA-Z]*$");
        Matcher mh6 = pt6.matcher(value);
        boolean matchFound6 = mh6.matches();
        if (!(matchFound6)) {
            JOptionPane.showMessageDialog(null, "Enter the Characters only");
            locationJTextField1.setText("");
            locationJTextField1.requestFocus();
        }
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_locationJTextField1FocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton1;
    private javax.swing.JButton createEnterpriseJButton1;
    private javax.swing.JComboBox enterpriseTypeJComboBox1;
    private javax.swing.JLabel imageJLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField locationJTextField1;
    private javax.swing.JTextField namejTextField1;
    // End of variables declaration//GEN-END:variables
}
