/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.EcoSystemAdmin;

import System.EcoSystem;
import System.Network.Network;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author SURAJ
 */
public class CreateNetworkJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    /**
     * Creates new form CreateNetworkJPanel
     */
    public CreateNetworkJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.system= system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createNetworkJButton1 = new javax.swing.JButton();
        backJButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nameJTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        locationJTextField1 = new javax.swing.JTextField();
        imageJLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createNetworkJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save_icon.gif"))); // NOI18N
        createNetworkJButton1.setText("Create");
        createNetworkJButton1.setToolTipText("Create Network");
        createNetworkJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createNetworkJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNetworkJButton1ActionPerformed(evt);
            }
        });
        add(createNetworkJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 100, 30));

        backJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backbutton.png"))); // NOI18N
        backJButton1.setText("Back");
        backJButton1.setToolTipText("Back");
        backJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });
        add(backJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 90, -1));

        jLabel4.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/create icon.png"))); // NOI18N
        jLabel4.setText("Create Network");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 280, 60));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Create Network", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Apple Braille", 1, 14))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(2, 2, 0, 4));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("Enter Network Name :");
        jPanel1.add(jLabel3);

        nameJTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameJTextField2FocusLost(evt);
            }
        });
        jPanel1.add(nameJTextField2);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setText("Enter Network Location :");
        jPanel1.add(jLabel1);

        locationJTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                locationJTextField1FocusLost(evt);
            }
        });
        jPanel1.add(locationJTextField1);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 450, 110));

        imageJLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        imageJLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/110637_SystemManagebackgroundPanel.jpg"))); // NOI18N
        add(imageJLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void createNetworkJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNetworkJButton1ActionPerformed

        String name= nameJTextField2.getText();
        String location = locationJTextField1.getText();
        if(name.isEmpty()||location.isEmpty()){
            JOptionPane.showMessageDialog(null, "One or more fields are Empty","", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        boolean locationExists= system.checkLocation(location);
        if(!locationExists)
        {
            Network n= system.createAndAddNetwork();
            n.setName(name);
            n.setLocationName(location);
            JOptionPane.showMessageDialog(null, "Network Created Successfully"," ", JOptionPane.INFORMATION_MESSAGE);
            userProcessContainer.remove(this);
            ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
        }
        else {
            JOptionPane.showMessageDialog(null, "Please enter different \n Location for this Network","Network Duplication",JOptionPane.ERROR_MESSAGE);
            nameJTextField2.setBackground(Color.yellow);
            locationJTextField1.setBackground(Color.yellow);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_createNetworkJButton1ActionPerformed

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed

        userProcessContainer.remove(this);
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_backJButton1ActionPerformed

    private void nameJTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameJTextField2FocusLost
    String value = nameJTextField2.getText();
        if (value.equals("")) {
        } else {
        Pattern pt6 = Pattern.compile("^[a-zA-Z\\ ]*$");
        Matcher mh6 = pt6.matcher(value);
        boolean matchFound6 = mh6.matches();
        if (!(matchFound6)) {
            JOptionPane.showMessageDialog(null, "Enter the Characters only");
            nameJTextField2.setText("");
            nameJTextField2.requestFocus();
        }
    }    // TODO add your handling code here:
    }//GEN-LAST:event_nameJTextField2FocusLost

    private void locationJTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_locationJTextField1FocusLost
        String value = locationJTextField1.getText();
        if (value.equals("")) {
        } else {
        Pattern pt6 = Pattern.compile("^[a-zA-Z]*$");
        Matcher mh6 = pt6.matcher(value);
        boolean matchFound6 = mh6.matches();
        if (!(matchFound6)) {
            JOptionPane.showMessageDialog(null, "Enter the Characters only");
            locationJTextField1.setText("");
            locationJTextField1.requestFocus();
        }
    }// TODO add your handling code here:
    }//GEN-LAST:event_locationJTextField1FocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton1;
    private javax.swing.JButton createNetworkJButton1;
    private javax.swing.JLabel imageJLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField locationJTextField1;
    private javax.swing.JTextField nameJTextField2;
    // End of variables declaration//GEN-END:variables
}
