/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.EcoSystemAdmin;

import java.awt.CardLayout;
import javax.swing.JPanel;
import System.EcoSystem;
import System.Person.Person;
import System.UserAccount.EmployeeUserAccount;

/**
 *
 * @author SURAJ
 */
public class EcoSystemAdminWorkAreaJPanel extends javax.swing.JPanel {

       private JPanel userProcessContainer;
       private EcoSystem system;
       private Person person;
    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    public EcoSystemAdminWorkAreaJPanel(JPanel userProcessContainer, EcoSystem system, EmployeeUserAccount userAccount) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.system= system;
        
        for(Person p: system.getPersonDirectory().getPersonlist())
        if(p.getPersonID()==(userAccount.getEmployee().getPerson().getPersonID()))
        {
            person=p;
            nameJLabel3.setText(p.getFirstName()+" "+p.getLastName());
        }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageNetworkJButton1 = new javax.swing.JButton();
        manageUserAccountsButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameJLabel3 = new javax.swing.JLabel();
        manageEmployeeJButton2 = new javax.swing.JButton();
        managePersonButton3 = new javax.swing.JButton();
        manageEnterpriseJButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        imageJLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageNetworkJButton1.setFont(new java.awt.Font("Apple Braille", 1, 13)); // NOI18N
        manageNetworkJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Manage Icon.png"))); // NOI18N
        manageNetworkJButton1.setText("Manage Network");
        manageNetworkJButton1.setToolTipText("Manage Network");
        manageNetworkJButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageNetworkJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageNetworkJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNetworkJButton1ActionPerformed(evt);
            }
        });
        add(manageNetworkJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 240, 60));

        manageUserAccountsButton1.setFont(new java.awt.Font("Apple Braille", 1, 13)); // NOI18N
        manageUserAccountsButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Manage User Accounts.png"))); // NOI18N
        manageUserAccountsButton1.setText("Manage User Account");
        manageUserAccountsButton1.setToolTipText("Manage User Account");
        manageUserAccountsButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageUserAccountsButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageUserAccountsButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserAccountsButton1ActionPerformed(evt);
            }
        });
        add(manageUserAccountsButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 570, 240, 60));

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("System Administrator Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 360, 60));

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 1, 16)); // NOI18N
        jLabel2.setText("Name :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, 30));

        nameJLabel3.setFont(new java.awt.Font("Arial Unicode MS", 1, 16)); // NOI18N
        add(nameJLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 170, 30));

        manageEmployeeJButton2.setFont(new java.awt.Font("Apple Braille", 1, 13)); // NOI18N
        manageEmployeeJButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Manage Employee.png"))); // NOI18N
        manageEmployeeJButton2.setText("Manage Employee");
        manageEmployeeJButton2.setToolTipText("Manage Employee Profiles");
        manageEmployeeJButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageEmployeeJButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageEmployeeJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeJButton2ActionPerformed(evt);
            }
        });
        add(manageEmployeeJButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 240, 60));

        managePersonButton3.setFont(new java.awt.Font("Apple Braille", 1, 13)); // NOI18N
        managePersonButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/manage_person.png"))); // NOI18N
        managePersonButton3.setText("Manage Person");
        managePersonButton3.setToolTipText("Manage Person Profiles");
        managePersonButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        managePersonButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        managePersonButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePersonButton3ActionPerformed(evt);
            }
        });
        add(managePersonButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 240, 60));

        manageEnterpriseJButton2.setFont(new java.awt.Font("Apple Braille", 1, 13)); // NOI18N
        manageEnterpriseJButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Manage Icon.png"))); // NOI18N
        manageEnterpriseJButton2.setText("Manage Enterprise");
        manageEnterpriseJButton2.setToolTipText("Manage Enterprise");
        manageEnterpriseJButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageEnterpriseJButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageEnterpriseJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseJButton2ActionPerformed(evt);
            }
        });
        add(manageEnterpriseJButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 240, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Manage Person.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 690, 250));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/network-2.png"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 690, 230));

        imageJLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        imageJLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/System admin Back Image.jpg"))); // NOI18N
        add(imageJLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 690));
    }// </editor-fold>//GEN-END:initComponents

    private void manageNetworkJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNetworkJButton1ActionPerformed

        ManageNetworkJPanel manageNetworkJPanel = new ManageNetworkJPanel(userProcessContainer, system, person);
        userProcessContainer.add("manageNetworkJPanel", manageNetworkJPanel);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_manageNetworkJButton1ActionPerformed

    private void manageUserAccountsButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserAccountsButton1ActionPerformed

        ManageEnterpriseUserAccountJPanel manageNetworkUserAccountJPanel= new ManageEnterpriseUserAccountJPanel(userProcessContainer, system, person);
        userProcessContainer.add("ManageNetworkUserAccountJPanel", manageNetworkUserAccountJPanel);
       ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_manageUserAccountsButton1ActionPerformed

    private void manageEmployeeJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeJButton2ActionPerformed
       
        ManageEnterpriseEmployeeJPanel manageEmployeeJPanel= new ManageEnterpriseEmployeeJPanel(userProcessContainer, person, system);
        userProcessContainer.add("ManageEmployeeJPanel", manageEmployeeJPanel);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_manageEmployeeJButton2ActionPerformed

    private void managePersonButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePersonButton3ActionPerformed
        
        ManageEnterprisePersonJPanel managePersonJPanel= new ManageEnterprisePersonJPanel(userProcessContainer, system, person);
        userProcessContainer.add("ManagePersonJPanel", managePersonJPanel);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_managePersonButton3ActionPerformed

    private void manageEnterpriseJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseJButton2ActionPerformed

        ManageEnterpriseJPanel manageEnterpriseJPanel= new ManageEnterpriseJPanel(userProcessContainer, system, person);
        userProcessContainer.add("ManageEnterpriseJPanel", manageEnterpriseJPanel);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_manageEnterpriseJButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageJLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton manageEmployeeJButton2;
    private javax.swing.JButton manageEnterpriseJButton2;
    private javax.swing.JButton manageNetworkJButton1;
    private javax.swing.JButton managePersonButton3;
    private javax.swing.JButton manageUserAccountsButton1;
    private javax.swing.JLabel nameJLabel3;
    // End of variables declaration//GEN-END:variables
}
