/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.EcoSystemAdmin;

import Interface.Organizations.CreateEmployeeJPanel;
import Interface.Organizations.ViewEmployeeJPanel;
import System.EcoSystem;
import System.Employee.Employee;
import System.Enterprise.Enterprise;
import System.Network.Network;
import System.Person.Person;
import System.UserAccount.EmployeeUserAccount;
import System.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SURAJ
 */
public class ManageEnterpriseEmployeeJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system; 
    /**
     * Creates new form ManageEmployeeJPanel
     */
    public ManageEnterpriseEmployeeJPanel(JPanel userProcessContainer, Person p, EcoSystem system) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.system= system;
        nameJLabel3.setText(p.getFirstName()+" "+p.getLastName());
        populateNetworkComboBox();
    }

    private void populateNetworkComboBox()
    {
       networkJComboBox1.removeAllItems();
       for(Network network: system.getNetworkList())
          networkJComboBox1.addItem(network);
    }
     private void populateEnterpriseComboBox(Network n)
    {
       enterpriseJComboBox1.removeAllItems();
       for(Enterprise e: n.getEnterpriseList())
          enterpriseJComboBox1.addItem(e);
    }

    private void populateEmployeeTable(Enterprise enterprise)
    {
        DefaultTableModel model = (DefaultTableModel) employeeJTable1.getModel();
        model.setRowCount(0);
        for(Employee e: enterprise.getEmployeeDirectory().getEmployeeList()){
            Object[] row = new Object[4];
            row[0]= e;
            row[1]= e.getEmpID();
            row[2]= e.getPerson().getAge();
            row[3]= e.getPerson().getGender();
            model.addRow(row);
         }   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        networkJComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeeJTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameJLabel3 = new javax.swing.JLabel();
        backJButton1 = new javax.swing.JButton();
        addEmployeeJButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        selectedEmployeeJLabel6 = new javax.swing.JLabel();
        deleteEmployeeJButton1 = new javax.swing.JButton();
        viewEmployeeJKButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        enterpriseJComboBox1 = new javax.swing.JComboBox();
        refreshButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        imageJLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        networkJComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkJComboBox1ActionPerformed(evt);
            }
        });
        add(networkJComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 200, 30));

        employeeJTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Employee Name", "Employee ID", "Age", "Gender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        employeeJTable1.setToolTipText("Person Table");
        employeeJTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        employeeJTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeJTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(employeeJTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 650, 210));

        jLabel5.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Manage Icon.png"))); // NOI18N
        jLabel5.setText("Manage Enterprise Employees");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 340, 60));

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 1, 16)); // NOI18N
        jLabel6.setText("Name :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, 30));

        nameJLabel3.setFont(new java.awt.Font("Arial Unicode MS", 1, 16)); // NOI18N
        add(nameJLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 170, 30));

        backJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backbutton.png"))); // NOI18N
        backJButton1.setText("Back");
        backJButton1.setToolTipText("Back");
        backJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });
        add(backJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 610, 100, -1));

        addEmployeeJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/GoIcon.gif"))); // NOI18N
        addEmployeeJButton1.setText("Add Employee");
        addEmployeeJButton1.setToolTipText("Create Employee Profile");
        addEmployeeJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addEmployeeJButton1.setEnabled(false);
        addEmployeeJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeJButton1ActionPerformed(evt);
            }
        });
        add(addEmployeeJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 560, 150, 30));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel9.setText("Employee in Enterprise :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 200, 30));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel10.setText("Create Employee :");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 140, 30));

        selectedEmployeeJLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        add(selectedEmployeeJLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 190, 30));

        deleteEmployeeJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete_icon.png"))); // NOI18N
        deleteEmployeeJButton1.setText("Delete Employee");
        deleteEmployeeJButton1.setToolTipText("Delete Employee");
        deleteEmployeeJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteEmployeeJButton1.setEnabled(false);
        deleteEmployeeJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEmployeeJButton1ActionPerformed(evt);
            }
        });
        add(deleteEmployeeJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 540, 150, 30));

        viewEmployeeJKButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon small.gif"))); // NOI18N
        viewEmployeeJKButton2.setText("View Employee");
        viewEmployeeJKButton2.setToolTipText("View Employee Details");
        viewEmployeeJKButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewEmployeeJKButton2.setEnabled(false);
        viewEmployeeJKButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEmployeeJKButton2ActionPerformed(evt);
            }
        });
        add(viewEmployeeJKButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 500, 150, 30));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel11.setText("Selected Employee Name :");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, -1, 30));

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel13.setText("Select a Network :");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, 20));

        enterpriseJComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseJComboBox1ActionPerformed(evt);
            }
        });
        add(enterpriseJComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 200, 30));

        refreshButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset-icon.png"))); // NOI18N
        refreshButton3.setText("Refresh");
        refreshButton3.setToolTipText("Refresh Table");
        refreshButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refreshButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButton3ActionPerformed(evt);
            }
        });
        add(refreshButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 120, 30));

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel14.setText("Select an Enterprise :");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, 30));

        imageJLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        imageJLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/110637_SystemManagebackgroundPanel.jpg"))); // NOI18N
        add(imageJLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void networkJComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkJComboBox1ActionPerformed

        Network n = (Network) networkJComboBox1.getSelectedItem();
         if(n != null)populateEnterpriseComboBox(n);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_networkJComboBox1ActionPerformed

    private void employeeJTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeJTable1MouseClicked

        int selectedRow= employeeJTable1.getSelectedRow();
        if (selectedRow < 0) return;
        Employee employee =  (Employee) employeeJTable1.getValueAt(selectedRow, 0);
        if(employee!=null)
        {selectedEmployeeJLabel6.setText(employee.getPerson().getFirstName()+" "+ employee.getPerson().getLastName());
        viewEmployeeJKButton2.setEnabled(true);
        deleteEmployeeJButton1.setEnabled(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeJTable1MouseClicked

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_backJButton1ActionPerformed

    private void addEmployeeJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeJButton1ActionPerformed

        Enterprise e= (Enterprise) enterpriseJComboBox1.getSelectedItem();
        CreateEmployeeJPanel createEmployeeJPanel = new CreateEmployeeJPanel(userProcessContainer, e, null);
        userProcessContainer.add("CreateEmployeeJPanel", createEmployeeJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_addEmployeeJButton1ActionPerformed

    private void deleteEmployeeJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEmployeeJButton1ActionPerformed

        Enterprise e= (Enterprise) enterpriseJComboBox1.getSelectedItem();
        int selectedRow= employeeJTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row","Invalid Action", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Employee employee= (Employee) employeeJTable1.getValueAt(selectedRow, 0);

        int dialogButton = JOptionPane.YES_NO_OPTION;
        int response =JOptionPane.showConfirmDialog(null, "Are you sure to delete "+ employee.getPerson().getFirstName()+" "+employee.getPerson().getLastName() +" ?", "Delete Confirmation", dialogButton, JOptionPane.WARNING_MESSAGE);
        if(response == JOptionPane.YES_OPTION)
        { 
         ArrayList<EmployeeUserAccount> local1 = new ArrayList<>(); 
         for(UserAccount ua: e.getUserAccountDirectory().getUserAccountList())
           if(((EmployeeUserAccount)ua).getEmployee().getEmpID()==(employee.getEmpID()))
               local1.add((EmployeeUserAccount) ua);
         for(UserAccount ua: local1) e.getUserAccountDirectory().getUserAccountList().remove(ua);
         e.getEmployeeDirectory().getEmployeeList().remove(employee);
         selectedEmployeeJLabel6.setText("");
         populateEmployeeTable(e);
         viewEmployeeJKButton2.setEnabled(false);
         deleteEmployeeJButton1.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteEmployeeJButton1ActionPerformed

    private void viewEmployeeJKButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEmployeeJKButton2ActionPerformed

        int selectedRow= employeeJTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row","Invalid Action", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Employee employee= (Employee) employeeJTable1.getValueAt(selectedRow, 0);

        ViewEmployeeJPanel viewUpdateEmployeeJPanel = new ViewEmployeeJPanel(userProcessContainer, employee);
        userProcessContainer.add("ViewUpdateEmployeeJPanel", viewUpdateEmployeeJPanel);
         ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_viewEmployeeJKButton2ActionPerformed

    private void enterpriseJComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseJComboBox1ActionPerformed
        Enterprise e= (Enterprise) enterpriseJComboBox1.getSelectedItem();
        if(e != null){populateEmployeeTable(e);
        addEmployeeJButton1.setEnabled(true);
        selectedEmployeeJLabel6.setText("");}
        // TODO add your handling code here:
    }//GEN-LAST:event_enterpriseJComboBox1ActionPerformed

    private void refreshButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButton3ActionPerformed
        Enterprise e= (Enterprise) enterpriseJComboBox1.getSelectedItem();
        if(e != null) populateEmployeeTable(e);
        viewEmployeeJKButton2.setEnabled(false);
        deleteEmployeeJButton1.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmployeeJButton1;
    private javax.swing.JButton backJButton1;
    private javax.swing.JButton deleteEmployeeJButton1;
    private javax.swing.JTable employeeJTable1;
    private javax.swing.JComboBox enterpriseJComboBox1;
    private javax.swing.JLabel imageJLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameJLabel3;
    private javax.swing.JComboBox networkJComboBox1;
    private javax.swing.JButton refreshButton3;
    private javax.swing.JLabel selectedEmployeeJLabel6;
    private javax.swing.JButton viewEmployeeJKButton2;
    // End of variables declaration//GEN-END:variables
}
