/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.EcoSystemAdmin;

import Interface.Organizations.CreateUserAccountJPanel;
import System.Network.Network;
import System.EcoSystem;
import System.Enterprise.Enterprise;
import System.Person.Person;
import System.UserAccount.EmployeeUserAccount;
import System.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SURAJ
 */
public class ManageEnterpriseUserAccountJPanel extends javax.swing.JPanel {

     private EcoSystem system;
     private JPanel userProcessContainer;
    /**
     * Creates new form CreateEnterpriceJPanel
     */
    public ManageEnterpriseUserAccountJPanel(JPanel userProcessContainer,EcoSystem system, Person p) {
        initComponents();
        this.system= system;
        this.userProcessContainer= userProcessContainer;
        nameJLabel3.setText(p.getFirstName()+" "+p.getLastName());
        populateNetworkComboBox();
        
    }
    
    private void populateNetworkComboBox()
    {
       networkJComboBox1.removeAllItems();
       for(Network network: system.getNetworkList())
          networkJComboBox1.addItem(network);
    }

     private void populateEnterpriseComboBox(Network n)
    {
       enterpriseJComboBox1.removeAllItems();
       for(Enterprise e: n.getEnterpriseList())
          enterpriseJComboBox1.addItem(e);
    }
     
    private void populateUserAccountTable(Enterprise e)
    {
        DefaultTableModel model = (DefaultTableModel) userAccountJTable1.getModel();
        model.setRowCount(0);
        for(UserAccount ua: e.getUserAccountDirectory().getUserAccountList()){
            Object[] row = new Object[2];
            row[0]= (EmployeeUserAccount) ua;
            row[1]= ua.getUsername();
            model.addRow(row);
         }   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        networkJComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        userAccountJTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameJLabel3 = new javax.swing.JLabel();
        backJButton1 = new javax.swing.JButton();
        createUserAccountJButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        enterpriseJComboBox1 = new javax.swing.JComboBox();
        refreshButton3 = new javax.swing.JButton();
        deleteUserAccountJButton2 = new javax.swing.JButton();
        imageJLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        networkJComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkJComboBox1ActionPerformed(evt);
            }
        });
        add(networkJComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 200, 30));

        userAccountJTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Person Name", "Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        userAccountJTable1.setToolTipText("Enterprise Table");
        userAccountJTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userAccountJTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userAccountJTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(userAccountJTable1);
        userAccountJTable1.getColumnModel().getColumn(0).setResizable(false);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 650, 190));

        jLabel5.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Manage Icon.png"))); // NOI18N
        jLabel5.setText("Manage Enterprise Administrator Accounts");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 510, 60));

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 1, 16)); // NOI18N
        jLabel6.setText("Name :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, 30));

        nameJLabel3.setFont(new java.awt.Font("Arial Unicode MS", 1, 16)); // NOI18N
        add(nameJLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 170, 30));

        backJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backbutton.png"))); // NOI18N
        backJButton1.setText("Back");
        backJButton1.setToolTipText("Back");
        backJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });
        add(backJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 100, -1));

        createUserAccountJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/GoIcon.gif"))); // NOI18N
        createUserAccountJButton1.setText("Add Account");
        createUserAccountJButton1.setToolTipText("Add New Account");
        createUserAccountJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createUserAccountJButton1.setEnabled(false);
        createUserAccountJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserAccountJButton1ActionPerformed(evt);
            }
        });
        add(createUserAccountJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, 130, 30));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel9.setText("Administrator Accounts :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, 30));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel10.setText("Create New Account :");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 160, 30));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel12.setText("Select an Enterprise :");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, 20));

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel13.setText("Select a Network :");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        enterpriseJComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseJComboBox1ActionPerformed(evt);
            }
        });
        add(enterpriseJComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 200, 30));

        refreshButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset-icon.png"))); // NOI18N
        refreshButton3.setText("Refresh");
        refreshButton3.setToolTipText("Refresh Table");
        refreshButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refreshButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButton3ActionPerformed(evt);
            }
        });
        add(refreshButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 110, 30));

        deleteUserAccountJButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete_icon.png"))); // NOI18N
        deleteUserAccountJButton2.setText("Delete Account");
        deleteUserAccountJButton2.setToolTipText("Delete User Account");
        deleteUserAccountJButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteUserAccountJButton2.setEnabled(false);
        deleteUserAccountJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserAccountJButton2ActionPerformed(evt);
            }
        });
        add(deleteUserAccountJButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 490, 150, -1));

        imageJLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        imageJLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/110637_SystemManagebackgroundPanel.jpg"))); // NOI18N
        add(imageJLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_backJButton1ActionPerformed

    private void createUserAccountJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserAccountJButton1ActionPerformed

        Enterprise e= (Enterprise) enterpriseJComboBox1.getSelectedItem();
        if(e == null)
        {
          JOptionPane.showMessageDialog(null, "Please select an Enterprise","Invalid Action", JOptionPane.WARNING_MESSAGE);
          return;
        }
        CreateUserAccountJPanel createOrganizationUserAccountJPanel= new CreateUserAccountJPanel(userProcessContainer, system, e, null);
        userProcessContainer.add("CreateOrganizationUserAccountJPanel", createOrganizationUserAccountJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_createUserAccountJButton1ActionPerformed

    private void networkJComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkJComboBox1ActionPerformed

        Network n = (Network) networkJComboBox1.getSelectedItem();
         if(n != null)populateEnterpriseComboBox(n);
        // TODO add your handling code here:
    }//GEN-LAST:event_networkJComboBox1ActionPerformed

    private void enterpriseJComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseJComboBox1ActionPerformed
        Enterprise e= (Enterprise) enterpriseJComboBox1.getSelectedItem();
        if(e != null){populateUserAccountTable(e);
        createUserAccountJButton1.setEnabled(true);}
        // TODO add your handling code here:
    }//GEN-LAST:event_enterpriseJComboBox1ActionPerformed

    private void userAccountJTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userAccountJTable1MouseClicked
        int selectedRow= userAccountJTable1.getSelectedRow();
        if (selectedRow < 0) return;
        UserAccount ua = (UserAccount) userAccountJTable1.getValueAt(selectedRow, 0);
        if(ua!=null) deleteUserAccountJButton2.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_userAccountJTable1MouseClicked

    private void refreshButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButton3ActionPerformed
        Enterprise e= (Enterprise) enterpriseJComboBox1.getSelectedItem();
         if(e != null)populateUserAccountTable(e);
        deleteUserAccountJButton2.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshButton3ActionPerformed

    private void deleteUserAccountJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserAccountJButton2ActionPerformed
       
        Enterprise e= (Enterprise) enterpriseJComboBox1.getSelectedItem();
        int selectedRow= userAccountJTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Row","Invalid Action", JOptionPane.WARNING_MESSAGE);
            return;
        }
        EmployeeUserAccount ua= (EmployeeUserAccount) userAccountJTable1.getValueAt(selectedRow, 0);
        
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int response = JOptionPane.showConfirmDialog(null, "Are you sure to delete "+ ua.getEmployee().getPerson().getFirstName()+" "+ua.getEmployee().getPerson().getLastName()+" ?", 
                    "Delete Confirmation", dialogButton, JOptionPane.WARNING_MESSAGE);
        if(response == JOptionPane.YES_OPTION)
            e.getUserAccountDirectory().getUserAccountList().remove(ua);
            populateUserAccountTable(e);
            deleteUserAccountJButton2.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteUserAccountJButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton1;
    private javax.swing.JButton createUserAccountJButton1;
    private javax.swing.JButton deleteUserAccountJButton2;
    private javax.swing.JComboBox enterpriseJComboBox1;
    private javax.swing.JLabel imageJLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameJLabel3;
    private javax.swing.JComboBox networkJComboBox1;
    private javax.swing.JButton refreshButton3;
    private javax.swing.JTable userAccountJTable1;
    // End of variables declaration//GEN-END:variables
}
