/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.EcoSystemAdmin;

import System.Network.Network;
import javax.swing.table.DefaultTableModel;
import System.EcoSystem;
import System.Person.Person;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author SURAJ
 */
public class ManageNetworkJPanel extends javax.swing.JPanel {

    private EcoSystem system;
    private JPanel userProcessContainer;
    /**
     * Creates new form CreateNetworkJPanel
     */
    public ManageNetworkJPanel(JPanel userProcessContainer,EcoSystem system, Person p) {
        initComponents();
        this.system= system;
        this.userProcessContainer= userProcessContainer;
        nameJLabel3.setText(p.getFirstName()+" "+p.getLastName());
        populateTable();
    }
    
    private void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel) networkJTable1.getModel();
        model.setRowCount(0);
        
        for(Network network: system.getNetworkList()){
            Object[] row = new Object[2];
            row[0]= network;
            row[1]= network.getLocationName();
            model.addRow(row);
         }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        networkJTable1 = new javax.swing.JTable();
        createNetworkJButton1 = new javax.swing.JButton();
        backJButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameJLabel3 = new javax.swing.JLabel();
        deleteNetworkJButton1 = new javax.swing.JButton();
        viewNetworkJKButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        refreshButton1 = new javax.swing.JButton();
        imageJLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        networkJTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Network Location"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        networkJTable1.setToolTipText("Network Table");
        networkJTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        networkJTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                networkJTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(networkJTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 580, 172));

        createNetworkJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/addIcon.gif"))); // NOI18N
        createNetworkJButton1.setText("Add Network");
        createNetworkJButton1.setToolTipText("Create Network");
        createNetworkJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createNetworkJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNetworkJButton1ActionPerformed(evt);
            }
        });
        add(createNetworkJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 140, 30));

        backJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backbutton.png"))); // NOI18N
        backJButton1.setText("Back");
        backJButton1.setToolTipText("Back");
        backJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });
        add(backJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 80, -1));

        jLabel4.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Manage Icon.png"))); // NOI18N
        jLabel4.setText("Manage Networks");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 270, 60));

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 1, 16)); // NOI18N
        jLabel5.setText("Name :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, 30));

        nameJLabel3.setFont(new java.awt.Font("Arial Unicode MS", 1, 16)); // NOI18N
        add(nameJLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 170, 30));

        deleteNetworkJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete_icon.png"))); // NOI18N
        deleteNetworkJButton1.setText("Delete Network");
        deleteNetworkJButton1.setToolTipText("Delete Network");
        deleteNetworkJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteNetworkJButton1.setEnabled(false);
        deleteNetworkJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteNetworkJButton1ActionPerformed(evt);
            }
        });
        add(deleteNetworkJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 150, 30));

        viewNetworkJKButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon small.gif"))); // NOI18N
        viewNetworkJKButton2.setText("View Network");
        viewNetworkJKButton2.setToolTipText("View Network Details");
        viewNetworkJKButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewNetworkJKButton2.setEnabled(false);
        viewNetworkJKButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewNetworkJKButton2ActionPerformed(evt);
            }
        });
        add(viewNetworkJKButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 150, 30));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel7.setText("Networks :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel8.setText("Create a Network :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, 30));

        refreshButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset-icon.png"))); // NOI18N
        refreshButton1.setText("Refresh");
        refreshButton1.setToolTipText("Refresh");
        refreshButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refreshButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButton1ActionPerformed(evt);
            }
        });
        add(refreshButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 120, 30));

        imageJLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        imageJLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/110637_SystemManagebackgroundPanel.jpg"))); // NOI18N
        add(imageJLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void createNetworkJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNetworkJButton1ActionPerformed

        CreateNetworkJPanel createNetworkJPanel= new CreateNetworkJPanel(userProcessContainer, system);
        userProcessContainer.add("CreateNetworkJPanel", createNetworkJPanel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_createNetworkJButton1ActionPerformed

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_backJButton1ActionPerformed

    private void viewNetworkJKButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewNetworkJKButton2ActionPerformed
       
         int selectedRow= networkJTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row","Invalid Action", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Network n = (Network) networkJTable1.getValueAt(selectedRow, 0);
        
        ViewUpdateNetworkJPanel viewUpdateNetworkJPanel= new ViewUpdateNetworkJPanel(userProcessContainer, n);
        userProcessContainer.add("ViewUpdateNetworkJPanel", viewUpdateNetworkJPanel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_viewNetworkJKButton2ActionPerformed

    private void deleteNetworkJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteNetworkJButton1ActionPerformed

        int selectedRow= networkJTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row","Invalid Action", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Network n = (Network) networkJTable1.getValueAt(selectedRow, 0);
        
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int response =JOptionPane.showConfirmDialog(null, "Are you sure to delete "+ n.getName() +" ?", "Delete Confirmation", dialogButton, JOptionPane.WARNING_MESSAGE);
        if(response == JOptionPane.YES_OPTION)
            system.removeNetwork(n);
        populateTable();
        deleteNetworkJButton1.setEnabled(false);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteNetworkJButton1ActionPerformed

    private void networkJTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_networkJTable1MouseClicked

        viewNetworkJKButton2.setEnabled(true);
        deleteNetworkJButton1.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_networkJTable1MouseClicked

    private void refreshButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButton1ActionPerformed
       populateTable();
        viewNetworkJKButton2.setEnabled(false);
        deleteNetworkJButton1.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton1;
    private javax.swing.JButton createNetworkJButton1;
    private javax.swing.JButton deleteNetworkJButton1;
    private javax.swing.JLabel imageJLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameJLabel3;
    private javax.swing.JTable networkJTable1;
    private javax.swing.JButton refreshButton1;
    private javax.swing.JButton viewNetworkJKButton2;
    // End of variables declaration//GEN-END:variables
}
