/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.EcoSystemAdmin;

import Interface.Organizations.CreatePersonJPanel;
import Interface.Organizations.ViewUpdatePersonJPanel;
import System.EcoSystem;
import System.Employee.Employee;
import System.Enterprise.Enterprise;
import System.Network.Network;
import System.Person.Person;
import System.UserAccount.EmployeeUserAccount;
import System.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SURAJ
 */
public class ManageEnterprisePersonJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system; 
    /**
     * Creates new form ManagePersonJPanel
     */
    public ManageEnterprisePersonJPanel(JPanel userProcessContainer, EcoSystem system,Person p) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.system= system;
        nameJLabel3.setText(p.getFirstName()+" "+p.getLastName());
        populateNetworkComboBox();
    }

     private void populateNetworkComboBox()
    {
       networkJComboBox1.removeAllItems();
       for(Network network: system.getNetworkList())
          networkJComboBox1.addItem(network);
    }
     private void populateEnterpriseComboBox(Network n)
    {
       enterpriseJComboBox1.removeAllItems();
       for(Enterprise e: n.getEnterpriseList())
          enterpriseJComboBox1.addItem(e);
    }

    private void populatePersonTable(Enterprise e)
    {
        DefaultTableModel model = (DefaultTableModel) personJTable1.getModel();
        model.setRowCount(0);
        for(Person person: e.getPersonDirectory().getPersonlist()){
            Object[] row = new Object[4];
            row[0]= person;
            row[1]= person.getPersonID();
            row[2]= person.getAge();
            row[3]= person.getGender();
            model.addRow(row);
         }   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        networkJComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        personJTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameJLabel3 = new javax.swing.JLabel();
        backJButton1 = new javax.swing.JButton();
        addPersonJButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        selectedPersonJLabel6 = new javax.swing.JLabel();
        deletePersonJButton1 = new javax.swing.JButton();
        viewDetailsJButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        enterpriseJComboBox1 = new javax.swing.JComboBox();
        refreshButton3 = new javax.swing.JButton();
        imageJLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        networkJComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkJComboBox1ActionPerformed(evt);
            }
        });
        add(networkJComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 200, 30));

        personJTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Person ID", "Age", "Gender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        personJTable1.setToolTipText("Person Table");
        personJTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        personJTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                personJTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(personJTable1);
        personJTable1.getColumnModel().getColumn(2).setResizable(false);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 650, 140));

        jLabel5.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Manage Icon.png"))); // NOI18N
        jLabel5.setText("Manage Enterprise Person Profile");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 440, 60));

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 1, 16)); // NOI18N
        jLabel6.setText("Name :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, 30));

        nameJLabel3.setFont(new java.awt.Font("Arial Unicode MS", 1, 16)); // NOI18N
        add(nameJLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 170, 30));

        backJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backbutton.png"))); // NOI18N
        backJButton1.setText("Back");
        backJButton1.setToolTipText("Back");
        backJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });
        add(backJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, 100, -1));

        addPersonJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/addIcon.gif"))); // NOI18N
        addPersonJButton1.setText("Add Person");
        addPersonJButton1.setToolTipText("Add Person Profile");
        addPersonJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addPersonJButton1.setEnabled(false);
        addPersonJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPersonJButton1ActionPerformed(evt);
            }
        });
        add(addPersonJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, 130, 30));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel9.setText("Persons in Enterprise :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 170, 30));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel10.setText("Create a Person Profile :");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, 180, 30));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel12.setText("Select an Enterprise :");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, 30));

        selectedPersonJLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        add(selectedPersonJLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 190, 30));

        deletePersonJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete_icon.png"))); // NOI18N
        deletePersonJButton1.setText("Delete Person");
        deletePersonJButton1.setToolTipText("Delete Person Profile");
        deletePersonJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletePersonJButton1.setEnabled(false);
        deletePersonJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePersonJButton1ActionPerformed(evt);
            }
        });
        add(deletePersonJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 480, 150, 30));

        viewDetailsJButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon small.gif"))); // NOI18N
        viewDetailsJButton2.setText("View Details");
        viewDetailsJButton2.setToolTipText("View Person Details");
        viewDetailsJButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewDetailsJButton2.setEnabled(false);
        viewDetailsJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsJButton2ActionPerformed(evt);
            }
        });
        add(viewDetailsJButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 440, 150, 30));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel11.setText("Selected Person Name :");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, -1, 30));

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel13.setText("Select a Network :");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, 20));

        enterpriseJComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseJComboBox1ActionPerformed(evt);
            }
        });
        add(enterpriseJComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 200, 30));

        refreshButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset-icon.png"))); // NOI18N
        refreshButton3.setText("Refresh");
        refreshButton3.setToolTipText("Refresh Table");
        refreshButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refreshButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButton3ActionPerformed(evt);
            }
        });
        add(refreshButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 110, 30));

        imageJLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        imageJLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/110637_SystemManagebackgroundPanel.jpg"))); // NOI18N
        add(imageJLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void networkJComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkJComboBox1ActionPerformed

        Network n = (Network) networkJComboBox1.getSelectedItem();
        if(n != null)populateEnterpriseComboBox(n);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_networkJComboBox1ActionPerformed

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_backJButton1ActionPerformed

    private void addPersonJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPersonJButton1ActionPerformed

        Enterprise e= (Enterprise) enterpriseJComboBox1.getSelectedItem();
        CreatePersonJPanel createPersonJPanel= new CreatePersonJPanel(userProcessContainer, system, e, null);
        userProcessContainer.add("CreatePersonJPanel", createPersonJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_addPersonJButton1ActionPerformed

    private void deletePersonJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePersonJButton1ActionPerformed

        Enterprise e= (Enterprise) enterpriseJComboBox1.getSelectedItem();
        int selectedRow= personJTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row","Invalid Action", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Person p = (Person) personJTable1.getValueAt(selectedRow, 0);
        
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int response =JOptionPane.showConfirmDialog(null, "Are you sure to delete "+ p.getFirstName()+" "+p.getLastName() +" ?", "Delete Confirmation", dialogButton, JOptionPane.WARNING_MESSAGE);
        if(response == JOptionPane.YES_OPTION){
           ArrayList<Employee> local = new ArrayList<>();
           ArrayList<EmployeeUserAccount> local1 = new ArrayList<>(); 
        for(Employee employee: e.getEmployeeDirectory().getEmployeeList())
           if(employee.getPerson().getPersonID()==(p.getPersonID()))
           {
            for(UserAccount ua: e.getUserAccountDirectory().getUserAccountList())
              if(((EmployeeUserAccount)ua).getEmployee().getEmpID()==(employee.getEmpID()))
                   local1.add((EmployeeUserAccount) ua);
            local.add(employee);
           }
        for(Employee employee: local) e.getEmployeeDirectory().getEmployeeList().remove(employee);
        for(UserAccount ua: local1) e.getUserAccountDirectory().getUserAccountList().remove(ua);
        e.getPersonDirectory().deletePersonbyPersonID(p.getPersonID());
        populatePersonTable(e);
        deletePersonJButton1.setEnabled(false);
        viewDetailsJButton2.setEnabled(false);
        selectedPersonJLabel6.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_deletePersonJButton1ActionPerformed

    private void viewDetailsJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsJButton2ActionPerformed

        int selectedRow= personJTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row","Invalid Action", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Person p = (Person) personJTable1.getValueAt(selectedRow, 0);
        ViewUpdatePersonJPanel viewUpdatePersonJPanel= new ViewUpdatePersonJPanel(userProcessContainer, p);
        userProcessContainer.add("ViewUpdatePersonJPanel", viewUpdatePersonJPanel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

        // TODO add your handling code here:
    }//GEN-LAST:event_viewDetailsJButton2ActionPerformed

    private void enterpriseJComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseJComboBox1ActionPerformed
        Enterprise e= (Enterprise) enterpriseJComboBox1.getSelectedItem();
        if(e != null){
            populatePersonTable(e);
            addPersonJButton1.setEnabled(true);
            selectedPersonJLabel6.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_enterpriseJComboBox1ActionPerformed

    private void personJTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personJTable1MouseClicked

        int selectedRow= personJTable1.getSelectedRow();
        if (selectedRow < 0) return;
        Person p = (Person) personJTable1.getValueAt(selectedRow, 0);
        if(p!=null){
        selectedPersonJLabel6.setText(p.getFirstName()+" "+ p.getLastName());
        viewDetailsJButton2.setEnabled(true);
        deletePersonJButton1.setEnabled(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_personJTable1MouseClicked

    private void refreshButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButton3ActionPerformed
        Enterprise e= (Enterprise) enterpriseJComboBox1.getSelectedItem();
        if(e != null)populatePersonTable(e);
        viewDetailsJButton2.setEnabled(false);
        deletePersonJButton1.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPersonJButton1;
    private javax.swing.JButton backJButton1;
    private javax.swing.JButton deletePersonJButton1;
    private javax.swing.JComboBox enterpriseJComboBox1;
    private javax.swing.JLabel imageJLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameJLabel3;
    private javax.swing.JComboBox networkJComboBox1;
    private javax.swing.JTable personJTable1;
    private javax.swing.JButton refreshButton3;
    private javax.swing.JLabel selectedPersonJLabel6;
    private javax.swing.JButton viewDetailsJButton2;
    // End of variables declaration//GEN-END:variables
}
