/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.EcoSystemAdmin;

import System.Enterprise.Enterprise;
import System.Network.Network;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author SURAJ
 */
public class ViewUpdateEnterpriseJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Network network;
    /**
     * Creates new form UpdateEnterpriseJPanel
     */
    public ViewUpdateEnterpriseJPanel(JPanel userProcessContainer, Enterprise enterprise, Network network) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.enterprise= enterprise;
        this.network= network;
        populateFields();
    }

    private void populateFields()
    {
        namejTextField1.setText(enterprise.getName());
        locationjLabel3.setText(enterprise.getLocation());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        saveJButton1 = new javax.swing.JButton();
        backJButton1 = new javax.swing.JButton();
        updateJButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        namejTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        locationjLabel3 = new javax.swing.JLabel();
        imageJLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/View_icon.png"))); // NOI18N
        jLabel1.setText("View/Update Enterprise");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 330, 60));

        saveJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save_icon.gif"))); // NOI18N
        saveJButton1.setText("Save");
        saveJButton1.setToolTipText("Save Details");
        saveJButton1.setEnabled(false);
        saveJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJButton1ActionPerformed(evt);
            }
        });
        add(saveJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 100, 30));

        backJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backbutton.png"))); // NOI18N
        backJButton1.setText("Back");
        backJButton1.setToolTipText("Back");
        backJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });
        add(backJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 100, 30));

        updateJButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset-icon.png"))); // NOI18N
        updateJButton2.setText("Update");
        updateJButton2.setToolTipText("Update Enterprise");
        updateJButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateJButton2ActionPerformed(evt);
            }
        });
        add(updateJButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 100, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "View Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Apple Braille", 1, 14))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(2, 2, 0, 4));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Name :");
        jPanel1.add(jLabel5);

        namejTextField1.setEditable(false);
        namejTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                namejTextField1FocusLost(evt);
            }
        });
        jPanel1.add(namejTextField1);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Location :");
        jPanel1.add(jLabel6);
        jPanel1.add(locationjLabel3);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 450, 100));

        imageJLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        imageJLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/110637_SystemManagebackgroundPanel.jpg"))); // NOI18N
        add(imageJLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void saveJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJButton1ActionPerformed

        String name= namejTextField1.getText();
        if(name.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter Enterprise name","", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        Boolean exists= network.checkEnterpriseNameAndLocation(name, enterprise.getLocation());
        if(!exists)
        {
            enterprise.setName(name);
            JOptionPane.showMessageDialog(null, "Enterprise Updated Successfully","", JOptionPane.INFORMATION_MESSAGE);
            userProcessContainer.remove(this);
            ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
        }
        else  {
            JOptionPane.showMessageDialog(null, "Please enter different Enterprise Name","Information Duplication", JOptionPane.ERROR_MESSAGE);
            namejTextField1.setBackground(Color.yellow);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_saveJButton1ActionPerformed

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed

        userProcessContainer.remove(this);
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_backJButton1ActionPerformed

    private void updateJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateJButton2ActionPerformed

        namejTextField1.setEditable(true);
        saveJButton1.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_updateJButton2ActionPerformed

    private void namejTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namejTextField1FocusLost

        String value = namejTextField1.getText();
        if (value.equals("")) {
        } else {
        Pattern pt6 = Pattern.compile("^[a-zA-Z\\ ]*$");
        Matcher mh6 = pt6.matcher(value);
        boolean matchFound6 = mh6.matches();
        if (!(matchFound6)) {
            JOptionPane.showMessageDialog(null, "Enter the Characters only");
            namejTextField1.setText("");
            namejTextField1.requestFocus();
        }
    }// TODO add your handling code here:
    }//GEN-LAST:event_namejTextField1FocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton1;
    private javax.swing.JLabel imageJLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel locationjLabel3;
    private javax.swing.JTextField namejTextField1;
    private javax.swing.JButton saveJButton1;
    private javax.swing.JButton updateJButton2;
    // End of variables declaration//GEN-END:variables
}
