/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.AdExchangeEnterprise;

import Interface.Organizations.ManageOrganizationEmployeeJPanel;
import Interface.Organizations.ManageOrganizationJPanel;
import Interface.Organizations.ManageOrganizationUserAccountJPanel;
import Interface.Organizations.ManageOrganizationPersonJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;
import System.EcoSystem;
import System.Enterprise.AdExchange;
import System.Network.Network;
import System.Person.Person;
import System.UserAccount.EmployeeUserAccount;

/**
 *
 * @author SURAJ
 */
public class AdExchangeAdminWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private AdExchange exchange;
    private EcoSystem system;
    private Network network;
    private Person person;
    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public AdExchangeAdminWorkAreaJPanel(JPanel userProcessContainer,EcoSystem system,Network network , AdExchange exchange, EmployeeUserAccount userAccount) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.exchange= exchange;
        this.system= system;
        this.network=network;
        for(Person p: exchange.getPersonDirectory().getPersonlist())
        if(p.getPersonID()==(userAccount.getEmployee().getPerson().getPersonID()))
        {
            person= p;
            nameJLabel3.setText(p.getFirstName()+" "+p.getLastName());
        }
        enterpriseNameJLabel2.setText(exchange.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        enterpriseNameJLabel2 = new javax.swing.JLabel();
        nameJLabel3 = new javax.swing.JLabel();
        viewWoekRequestJButton4 = new javax.swing.JButton();
        manageOrgJButton1 = new javax.swing.JButton();
        manageUAJButton2 = new javax.swing.JButton();
        manageEmployeeJButton3 = new javax.swing.JButton();
        managePersonJButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        imageJLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Administrator Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 420, 60));

        enterpriseNameJLabel2.setFont(new java.awt.Font("Cambria", 0, 26)); // NOI18N
        enterpriseNameJLabel2.setForeground(new java.awt.Color(153, 51, 0));
        add(enterpriseNameJLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 320, 40));

        nameJLabel3.setFont(new java.awt.Font("Arial Unicode MS", 1, 16)); // NOI18N
        add(nameJLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 170, 30));

        viewWoekRequestJButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/work request icon.png"))); // NOI18N
        viewWoekRequestJButton4.setText("View Work Requests");
        viewWoekRequestJButton4.setToolTipText("View Work Requests");
        viewWoekRequestJButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewWoekRequestJButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewWoekRequestJButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewWoekRequestJButton4ActionPerformed(evt);
            }
        });
        add(viewWoekRequestJButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 550, 230, 50));

        manageOrgJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Manage Icon.png"))); // NOI18N
        manageOrgJButton1.setText("Manage Organization");
        manageOrgJButton1.setToolTipText("Manage Organization");
        manageOrgJButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageOrgJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageOrgJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrgJButton1ActionPerformed(evt);
            }
        });
        add(manageOrgJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 230, 50));

        manageUAJButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Manage User Accounts.png"))); // NOI18N
        manageUAJButton2.setText("Manage User Account");
        manageUAJButton2.setToolTipText("Manage User Account");
        manageUAJButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageUAJButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageUAJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUAJButton2ActionPerformed(evt);
            }
        });
        add(manageUAJButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 230, 50));

        manageEmployeeJButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Manage Employee.png"))); // NOI18N
        manageEmployeeJButton3.setText("Manage Employee");
        manageEmployeeJButton3.setToolTipText("Manage  Employee Profiles");
        manageEmployeeJButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageEmployeeJButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageEmployeeJButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeJButton3ActionPerformed(evt);
            }
        });
        add(manageEmployeeJButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 230, 50));

        managePersonJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/manage_person.png"))); // NOI18N
        managePersonJButton1.setText("Manage Person");
        managePersonJButton1.setToolTipText("Manage Person Profiles");
        managePersonJButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        managePersonJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        managePersonJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePersonJButton1ActionPerformed(evt);
            }
        });
        add(managePersonJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 230, 50));

        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 1, 16)); // NOI18N
        jLabel3.setText("Name :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Manage Organization.jpg"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 730, 160));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Request Icon.jpg"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, 730, 120));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Manage Person Small.png"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 730, 210));

        imageJLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        imageJLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AdExchange Background Title.jpg"))); // NOI18N
        add(imageJLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void viewWoekRequestJButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewWoekRequestJButton4ActionPerformed

        ViewWorkRequestsJPanel viewWorkRequestsJPanel= new ViewWorkRequestsJPanel(userProcessContainer, exchange, network);
        userProcessContainer.add("ViewWorkRequestsJPanel", viewWorkRequestsJPanel);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_viewWoekRequestJButton4ActionPerformed

    private void manageOrgJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrgJButton1ActionPerformed

        ManageOrganizationJPanel manageOrganizationJPanel= new ManageOrganizationJPanel(userProcessContainer, exchange, person);
        userProcessContainer.add("ManageOrganizationJPanel", manageOrganizationJPanel);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);

    }//GEN-LAST:event_manageOrgJButton1ActionPerformed

    private void manageUAJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUAJButton2ActionPerformed

        ManageOrganizationUserAccountJPanel manageOrganizationUserAccountJPanel= new ManageOrganizationUserAccountJPanel(userProcessContainer, system, exchange, person);
        userProcessContainer.add("ManageOrganizationUserAccountJPanel", manageOrganizationUserAccountJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_manageUAJButton2ActionPerformed

    private void manageEmployeeJButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeJButton3ActionPerformed

        ManageOrganizationEmployeeJPanel manageEmployeeAdvOrganizationJPanel= new ManageOrganizationEmployeeJPanel(userProcessContainer, person, exchange );
        userProcessContainer.add("ManageEmployeeAdvOrganizationJPanel", manageEmployeeAdvOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_manageEmployeeJButton3ActionPerformed

    private void managePersonJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePersonJButton1ActionPerformed

        ManageOrganizationPersonJPanel managePersonAdvEnterpriseJPanel = new ManageOrganizationPersonJPanel(userProcessContainer, system, exchange, person);
        userProcessContainer.add("ManagePersonAdvEnterpriseJPanel", managePersonAdvEnterpriseJPanel);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_managePersonJButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseNameJLabel2;
    private javax.swing.JLabel imageJLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton manageEmployeeJButton3;
    private javax.swing.JButton manageOrgJButton1;
    private javax.swing.JButton managePersonJButton1;
    private javax.swing.JButton manageUAJButton2;
    private javax.swing.JLabel nameJLabel3;
    private javax.swing.JButton viewWoekRequestJButton4;
    // End of variables declaration//GEN-END:variables
}
