/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Organizations;

import System.Employee.Employee;
import System.Enterprise.Enterprise;
import System.Organization.Organization;
import System.Person.Person;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SURAJ
 */
public class CreateEmployeeJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Organization organization;
    /**
     * Creates new form CreateEmployeeJPanel
     */
    public CreateEmployeeJPanel(JPanel userProcessContainer, Enterprise enterprise, Organization organization) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.enterprise=enterprise;
        this.organization= organization;
        if(enterprise != null)
           populatePersonTable(enterprise);
        else if(organization != null)
          populatePersonTable(organization);
    }
    
    private void populatePersonTable(Organization o)
    {
        DefaultTableModel model = (DefaultTableModel) personJTable1.getModel();
        model.setRowCount(0);
        for(Person person: o.getPersonDirectory().getPersonlist()){
            Object[] row = new Object[4];
            row[0]= person;
            row[1]= person.getPersonID();
            row[2]= person.getAge();
            row[3]= person.getGender();
            model.addRow(row);
         }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        personJTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        backJButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        employeeIDjTextField1 = new javax.swing.JTextField();
        createEmployeeJKButton2 = new javax.swing.JButton();
        selectedPersonJLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        imageJLabel1 = new javax.swing.JLabel();
        imageJLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        personJTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Person ID", "Age", "Gender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        personJTable1.setToolTipText("Person Table");
        personJTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        personJTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                personJTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(personJTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 650, 160));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel9.setText("Enter Employee Information :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 220, 30));

        jLabel5.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/create icon.png"))); // NOI18N
        jLabel5.setText(" Create Employee");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 330, 60));

        backJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backbutton.png"))); // NOI18N
        backJButton1.setText("Back");
        backJButton1.setToolTipText("Back");
        backJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });
        add(backJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 100, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel10.setText("Please select a person :");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 180, 30));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setText("Employee ID :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 100, 30));

        employeeIDjTextField1.setEnabled(false);
        employeeIDjTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                employeeIDjTextField1FocusLost(evt);
            }
        });
        add(employeeIDjTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 130, -1));

        createEmployeeJKButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save_icon.gif"))); // NOI18N
        createEmployeeJKButton2.setText("Create");
        createEmployeeJKButton2.setToolTipText("Create Employee");
        createEmployeeJKButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createEmployeeJKButton2.setEnabled(false);
        createEmployeeJKButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEmployeeJKButton2ActionPerformed(evt);
            }
        });
        add(createEmployeeJKButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 120, 30));

        selectedPersonJLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        add(selectedPersonJLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 190, 30));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel11.setText("Selected Person Name :");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, 30));

        imageJLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        add(imageJLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, -1));

        imageJLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        imageJLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Organization Background.jpg"))); // NOI18N
        add(imageJLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 690));
    }// </editor-fold>//GEN-END:initComponents

    private void personJTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personJTable1MouseClicked

        int selectedRow= personJTable1.getSelectedRow();
        if (selectedRow < 0) return;
        Person p = (Person) personJTable1.getValueAt(selectedRow, 0);
        if(p==null)return;
        selectedPersonJLabel6.setText(p.getFirstName()+" "+ p.getLastName());
        createEmployeeJKButton2.setEnabled(true);
        employeeIDjTextField1.setEnabled(true);
        
        
    }//GEN-LAST:event_personJTable1MouseClicked

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        userProcessContainer.remove(this);
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_backJButton1ActionPerformed

    private void createEmployeeJKButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEmployeeJKButton2ActionPerformed

        int selectedRow= personJTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row","Invalid Action", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Person p = (Person) personJTable1.getValueAt(selectedRow, 0);
        
        if(employeeIDjTextField1.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter a valid employeeID","", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if(employeeIDjTextField1.getText().length()!=4) return;
        if(employeeIDjTextField1.getText().contains("-")||employeeIDjTextField1.getText().contains("+")) return;
        int id;
        try {
            id= Integer.parseInt(employeeIDjTextField1.getText());
         } catch (Exception e) {
            return;
        }
        Boolean exists= null;
        if(enterprise != null)
            exists= enterprise.checkEnterpriseEmployeeIDs(id);
        else if(organization != null)
            exists= organization.getEmployeeDirectory().checkOrganizationEmployeeIDs(id);
        
        if(!exists)
        {
          Employee e = new Employee();
            e.setEmpID(id);
            e.setPerson(p);
            
            if(enterprise != null)
                 enterprise.getEmployeeDirectory().getEmployeeList().add(e);
             else if(organization != null)
                 organization.getEmployeeDirectory().getEmployeeList().add(e);
           JOptionPane.showMessageDialog(null, "Employee Created Successfully","", JOptionPane.INFORMATION_MESSAGE);
           employeeIDjTextField1.setText("");
           employeeIDjTextField1.setEnabled(false);
           createEmployeeJKButton2.setEnabled(false);
           selectedPersonJLabel6.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Please enter different EmployeeID","EmployeeID already exists", JOptionPane.ERROR_MESSAGE);
            employeeIDjTextField1.setBackground(Color.yellow);
            employeeIDjTextField1.setText("");
        }
     
    }//GEN-LAST:event_createEmployeeJKButton2ActionPerformed

    private void employeeIDjTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_employeeIDjTextField1FocusLost
        String value = employeeIDjTextField1.getText();
        if (value.equals("")) {
        } else {
        Pattern pt6 = Pattern.compile("^[0-9]*$");
        Matcher mh6 = pt6.matcher(value);
        boolean matchFound6 = mh6.matches();
        if (!(matchFound6)) {
            JOptionPane.showMessageDialog(null, "Enter the Numbers only");
            employeeIDjTextField1.setText("");
            employeeIDjTextField1.requestFocus();
        }else{
            if(value.length()!=4)
            { JOptionPane.showMessageDialog(null, "EmployeeID should be of 4 Digits");
                employeeIDjTextField1.setText("");
                employeeIDjTextField1.requestFocus();
            }
        }
    }   
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeIDjTextField1FocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton1;
    private javax.swing.JButton createEmployeeJKButton2;
    private javax.swing.JTextField employeeIDjTextField1;
    private javax.swing.JLabel imageJLabel1;
    private javax.swing.JLabel imageJLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable personJTable1;
    private javax.swing.JLabel selectedPersonJLabel6;
    // End of variables declaration//GEN-END:variables
}
