/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Organizations;

import System.EcoSystem;
import System.Employee.Employee;
import System.Enterprise.Enterprise;
import System.Organization.Organization;
import System.Role.AdminRole;
import System.Role.EmployeeRole;
import System.Role.Role;
import System.UserAccount.EmployeeUserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SURAJ
 */
public class CreateUserAccountJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer; 
    private EcoSystem system;
    private Organization organization;
    private Enterprise enterprise;
    /**
     * Creates new form CreateUserAccountJPanel
     */
    public CreateUserAccountJPanel(JPanel userProcessContainer,EcoSystem system, Enterprise enterprise, Organization organization) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system= system;
        this.enterprise=enterprise;
        this.organization=organization;
        if(enterprise != null){
           informationJLabel5.setText("Create Enterprise Administrator User Account");
           populatePersonTable(enterprise);
        }
        else if(organization != null)
        {
           informationJLabel5.setText("Create Organization Employee User Accounts");
           populatePersonTable(organization);
        }
        
    }
  private void populateRoleComboBox(Organization organization)
    {
       roleComboBox1.removeAllItems();
       for(Role role: organization.getOrganizationSupportedRole())
          roleComboBox1.addItem(role);
    }
    
   private void populatePersonTable(Organization organization)
    {
        DefaultTableModel model = (DefaultTableModel) employeeJTable1.getModel();
        model.setRowCount(0);
        for(Employee e: organization.getEmployeeDirectory().getEmployeeList()){
            Object[] row = new Object[4];
            row[0]= e;
            row[1]= e.getEmpID();
            row[2]= e.getPerson().getAge();
            row[3]= e.getPerson().getGender();
            model.addRow(row);
         }   
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createAccountJButton1 = new javax.swing.JButton();
        backJButton1 = new javax.swing.JButton();
        selectedEmployeeNameJLabel7 = new javax.swing.JLabel();
        informationJLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeeJTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        usernameTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        confirmjPasswordField2 = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        roleComboBox1 = new javax.swing.JComboBox();
        imageJLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createAccountJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save_icon.gif"))); // NOI18N
        createAccountJButton1.setText("Create");
        createAccountJButton1.setToolTipText("Create User Account");
        createAccountJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createAccountJButton1.setEnabled(false);
        createAccountJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountJButton1ActionPerformed(evt);
            }
        });
        add(createAccountJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 580, 100, 30));

        backJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backbutton.png"))); // NOI18N
        backJButton1.setText("Back");
        backJButton1.setToolTipText("Back");
        backJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });
        add(backJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 590, 90, -1));

        selectedEmployeeNameJLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        add(selectedEmployeeNameJLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 170, 30));

        informationJLabel5.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        informationJLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        informationJLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/create icon.png"))); // NOI18N
        informationJLabel5.setText("Create User Accounts");
        add(informationJLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 520, 60));

        employeeJTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Employee Name", "Employee ID", "Age", "Gender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        employeeJTable1.setToolTipText("Person Table");
        employeeJTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        employeeJTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeJTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(employeeJTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 650, 140));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel9.setText("Select Employee to Create Account :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 290, 30));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel8.setText("Selected Employee Name :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 190, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Create User Account", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Apple Braille", 1, 14))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(4, 2, 0, 4));

        jLabel6.setText("      Username :");
        jPanel1.add(jLabel6);

        usernameTextField1.setEditable(false);
        usernameTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameTextField1FocusLost(evt);
            }
        });
        jPanel1.add(usernameTextField1);

        jLabel7.setText("      Password :");
        jPanel1.add(jLabel7);

        jPasswordField1.setEditable(false);
        jPanel1.add(jPasswordField1);

        jLabel11.setText("      Confirm Password :");
        jPanel1.add(jLabel11);

        confirmjPasswordField2.setEditable(false);
        jPanel1.add(confirmjPasswordField2);

        jLabel10.setText("      Role :");
        jPanel1.add(jLabel10);

        roleComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Select-" }));
        roleComboBox1.setEnabled(false);
        roleComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(roleComboBox1);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 590, 170));

        imageJLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        imageJLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Organization Background.jpg"))); // NOI18N
        add(imageJLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 690));
    }// </editor-fold>//GEN-END:initComponents

    private void createAccountJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountJButton1ActionPerformed

        int selectedRow= employeeJTable1.getSelectedRow();
        if (selectedRow < 0) 
        {
           JOptionPane.showMessageDialog(null, "Please select an Employee","Invalid Action", JOptionPane.WARNING_MESSAGE);
           return;
        }
        Employee employee = (Employee) employeeJTable1.getValueAt(selectedRow, 0);
        
        String username= usernameTextField1.getText();
        if(!username.isEmpty()){
        char[] passchar = jPasswordField1.getPassword();
        String password = String.valueOf(passchar);
        if(!password.isEmpty())
        {
        char[] passcharconfirm = confirmjPasswordField2.getPassword();
        String confirmPassword = String.valueOf(passcharconfirm);
        if(password.equals(confirmPassword))
         {  Boolean exists= system.checkUsername(username,system);
           if(!exists){
               EmployeeUserAccount ua=  new EmployeeUserAccount();
               ua.setUsername(username);
               ua.setEmployee(employee);
               byte[] salt;
               String hashedPassword;
               if(enterprise != null){
                      salt = enterprise.getUserAccountDirectory().generateSalt();
                      hashedPassword= enterprise.getUserAccountDirectory().generateHashPassword(password, salt);
                      ua.setPassword(hashedPassword);
                      ua.setSalt(salt);
                      ua.setRole((AdminRole) roleComboBox1.getSelectedItem());
                      enterprise.getUserAccountDirectory().getUserAccountList().add(ua);
               }
               else if(organization!=null){
                     salt = organization.getUserAccountDirectory().generateSalt();
                     hashedPassword= organization.getUserAccountDirectory().generateHashPassword(password, salt);
                     ua.setPassword(hashedPassword);
                     ua.setSalt(salt);
                     ua.setRole((EmployeeRole) roleComboBox1.getSelectedItem());
                     organization.getUserAccountDirectory().getUserAccountList().add(ua);
               }
               JOptionPane.showMessageDialog(null, "UserAccount Created Successfully","", JOptionPane.INFORMATION_MESSAGE);
               usernameTextField1.setText("");
               jPasswordField1.setText("");
               confirmjPasswordField2.setText("");
               selectedEmployeeNameJLabel7.setText("");
               usernameTextField1.setEditable(false);
               jPasswordField1.setEditable(false);
               confirmjPasswordField2.setEditable(false);
               createAccountJButton1.setEnabled(false);
               roleComboBox1.setEnabled(false);
               usernameTextField1.setBackground(Color.white);
               jPasswordField1.setBackground(Color.white);
               confirmjPasswordField2.setBackground(Color.white);
           }else  {
                  JOptionPane.showMessageDialog(null, "Please Enter different Username","Username already Exists", JOptionPane.ERROR_MESSAGE);
                  usernameTextField1.setBackground(Color.yellow);
                  usernameTextField1.setText("");
            }
          }else {
                 JOptionPane.showMessageDialog(null, "Password does not match","Re-enter Password", JOptionPane.ERROR_MESSAGE);
                 jPasswordField1.setBackground(Color.YELLOW);
                 confirmjPasswordField2.setBackground(Color.YELLOW);
                 jPasswordField1.setText("");
                 confirmjPasswordField2.setText("");
           }
         }else {
                JOptionPane.showMessageDialog(null, "Please Enter a Password","Invalid Entry", JOptionPane.WARNING_MESSAGE);
                jPasswordField1.setBackground(Color.YELLOW);
          }
        }else {
               JOptionPane.showMessageDialog(null, "Please Enter a Username","Invalid Entry", JOptionPane.WARNING_MESSAGE);
               usernameTextField1.setBackground(Color.yellow);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_createAccountJButton1ActionPerformed

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_backJButton1ActionPerformed

    private void employeeJTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeJTable1MouseClicked

        int selectedRow= employeeJTable1.getSelectedRow();
        if (selectedRow < 0) return;
        Employee employee = (Employee) employeeJTable1.getValueAt(selectedRow, 0);
        if(employee==null)return;
        selectedEmployeeNameJLabel7.setText(employee.getPerson().getFirstName()+" "+ employee.getPerson().getLastName());
        usernameTextField1.setEditable(true);
        jPasswordField1.setEditable(true);
        confirmjPasswordField2.setEditable(true);
        roleComboBox1.setEnabled(true);
        if(enterprise != null)
           populateRoleComboBox(enterprise);
        else if(organization != null)
          populateRoleComboBox(organization);
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeJTable1MouseClicked

    private void roleComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleComboBox1ActionPerformed
        createAccountJButton1.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_roleComboBox1ActionPerformed

    private void usernameTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTextField1FocusLost
          String value = usernameTextField1.getText();
        if (value.equals("")) {
        } else {
        Pattern pt6 = Pattern.compile("^[a-zA-Z]*$");
        Matcher mh6 = pt6.matcher(value);
        boolean matchFound6 = mh6.matches();
        if (!(matchFound6)) {
            JOptionPane.showMessageDialog(null, "Enter the Characters only");
            usernameTextField1.setText("");
            usernameTextField1.requestFocus();
        }
    }   // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextField1FocusLost
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton1;
    private javax.swing.JPasswordField confirmjPasswordField2;
    private javax.swing.JButton createAccountJButton1;
    private javax.swing.JTable employeeJTable1;
    private javax.swing.JLabel imageJLabel2;
    private javax.swing.JLabel informationJLabel5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox roleComboBox1;
    private javax.swing.JLabel selectedEmployeeNameJLabel7;
    private javax.swing.JTextField usernameTextField1;
    // End of variables declaration//GEN-END:variables
}
