/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Organizations;

import System.Employee.Employee;
import System.Enterprise.Enterprise;
import System.Organization.Organization;
import System.Person.Person;
import System.UserAccount.EmployeeUserAccount;
import System.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SURAJ
 */
public class ManageOrganizationEmployeeJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    /**
     * Creates new form ManageEmployeeJPanel
     */
    public ManageOrganizationEmployeeJPanel(JPanel userProcessContainer, Person p, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.enterprise= enterprise;
        nameJLabel3.setText(p.getFirstName()+" "+p.getLastName());
        populateComboBox();
    }

    private void populateComboBox()
    {
        organizationJComboBox1.removeAllItems();
        for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList())
            organizationJComboBox1.addItem(organization);
    }
    
    private void populateEmployeeTable(Organization organization)
    {
        DefaultTableModel model = (DefaultTableModel) employeeJTable1.getModel();
        model.setRowCount(0);
        for(Employee e: organization.getEmployeeDirectory().getEmployeeList()){
            Object[] row = new Object[4];
            row[0]= e;
            row[1]= e.getEmpID();
            row[2]= e.getPerson().getAge();
            row[3]= e.getPerson().getGender();
            model.addRow(row);
         }   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        employeeJTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameJLabel3 = new javax.swing.JLabel();
        backJButton1 = new javax.swing.JButton();
        addEmployeeJButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        selectedEmployeeJLabel6 = new javax.swing.JLabel();
        deleteEmployeeJButton1 = new javax.swing.JButton();
        viewEmployeeJKButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        organizationJComboBox1 = new javax.swing.JComboBox();
        refreshButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        imageJLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeeJTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Employee Name", "Employee ID", "Age", "Gender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        employeeJTable1.setToolTipText("Employee Information Table");
        employeeJTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        employeeJTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeJTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(employeeJTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 650, 190));

        jLabel5.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Manage Icon.png"))); // NOI18N
        jLabel5.setText("Manage Organization Employees");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 400, 60));

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 1, 16)); // NOI18N
        jLabel6.setText("Name :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, 30));

        nameJLabel3.setFont(new java.awt.Font("Arial Unicode MS", 1, 16)); // NOI18N
        add(nameJLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 170, 30));

        backJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backbutton.png"))); // NOI18N
        backJButton1.setText("Back");
        backJButton1.setToolTipText("Back");
        backJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });
        add(backJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 590, 90, -1));

        addEmployeeJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/addIcon.gif"))); // NOI18N
        addEmployeeJButton1.setText("Add Employee");
        addEmployeeJButton1.setToolTipText("Add Employee");
        addEmployeeJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addEmployeeJButton1.setEnabled(false);
        addEmployeeJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeJButton1ActionPerformed(evt);
            }
        });
        add(addEmployeeJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 160, 30));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel9.setText("Employee in Organization :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 200, 30));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel10.setText("Create Employee :");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 140, 30));

        selectedEmployeeJLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        add(selectedEmployeeJLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 190, 30));

        deleteEmployeeJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete_icon.png"))); // NOI18N
        deleteEmployeeJButton1.setText("Delete Employee");
        deleteEmployeeJButton1.setToolTipText("Delete Employee Profile");
        deleteEmployeeJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteEmployeeJButton1.setEnabled(false);
        deleteEmployeeJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEmployeeJButton1ActionPerformed(evt);
            }
        });
        add(deleteEmployeeJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 490, 150, 30));

        viewEmployeeJKButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon small.gif"))); // NOI18N
        viewEmployeeJKButton2.setText("View Employee");
        viewEmployeeJKButton2.setToolTipText("View Employee Details");
        viewEmployeeJKButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewEmployeeJKButton2.setEnabled(false);
        viewEmployeeJKButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEmployeeJKButton2ActionPerformed(evt);
            }
        });
        add(viewEmployeeJKButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, 150, 30));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel11.setText("Selected Employee Name :");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, -1, 30));

        organizationJComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationJComboBox1ActionPerformed(evt);
            }
        });
        add(organizationJComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 190, 30));

        refreshButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset-icon.png"))); // NOI18N
        refreshButton3.setText("Refresh");
        refreshButton3.setToolTipText("Refresh Table");
        refreshButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refreshButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButton3ActionPerformed(evt);
            }
        });
        add(refreshButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, 110, 30));

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel14.setText("Select an Organization :");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, 30));

        imageJLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        imageJLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Organization Background.jpg"))); // NOI18N
        add(imageJLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 690));
    }// </editor-fold>//GEN-END:initComponents

    private void employeeJTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeJTable1MouseClicked

        int selectedRow= employeeJTable1.getSelectedRow();
        if (selectedRow < 0) return;
        Employee employee = (Employee) employeeJTable1.getValueAt(selectedRow, 0);
        if(employee!=null){
        selectedEmployeeJLabel6.setText(employee.getPerson().getFirstName()+" "+ employee.getPerson().getLastName());
        viewEmployeeJKButton2.setEnabled(true);
        deleteEmployeeJButton1.setEnabled(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeJTable1MouseClicked

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_backJButton1ActionPerformed

    private void addEmployeeJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeJButton1ActionPerformed

        Organization o= (Organization) organizationJComboBox1.getSelectedItem();
        if(o == null)
        {
             JOptionPane.showMessageDialog(null, "Please select an Organization","Invalid Action", JOptionPane.WARNING_MESSAGE);
             return;
        }
        CreateEmployeeJPanel createEmployeeJPanel = new CreateEmployeeJPanel(userProcessContainer,null ,o);
        userProcessContainer.add("CreateEmployeeJPanel", createEmployeeJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_addEmployeeJButton1ActionPerformed

    private void deleteEmployeeJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEmployeeJButton1ActionPerformed

        Organization o= (Organization) organizationJComboBox1.getSelectedItem();
        int selectedRow= employeeJTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row","Invalid Action", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Employee employee= (Employee) employeeJTable1.getValueAt(selectedRow, 0);

        int dialogButton = JOptionPane.YES_NO_OPTION;
        int response= JOptionPane.showConfirmDialog(null, "Are you sure to delete "+ employee.getPerson().getFirstName()+" "+employee.getPerson().getLastName() +" ?", "Delete Confirmation", dialogButton, JOptionPane.WARNING_MESSAGE);
        if(response == JOptionPane.YES_OPTION)
        {
         ArrayList<EmployeeUserAccount> local1 = new ArrayList<>(); 
         for(UserAccount ua: o.getUserAccountDirectory().getUserAccountList())
            if(((EmployeeUserAccount)ua).getEmployee().getEmpID()==(employee.getEmpID()))
                 local1.add((EmployeeUserAccount) ua);
         for(UserAccount ua: local1) o.getUserAccountDirectory().getUserAccountList().remove(ua);
           o.getEmployeeDirectory().getEmployeeList().remove(employee);
        populateEmployeeTable(o);
        deleteEmployeeJButton1.setEnabled(false);
        viewEmployeeJKButton2.setEnabled(false);
        selectedEmployeeJLabel6.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteEmployeeJButton1ActionPerformed

    private void viewEmployeeJKButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEmployeeJKButton2ActionPerformed

        int selectedRow= employeeJTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row","Invalid Action", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Employee employee= (Employee) employeeJTable1.getValueAt(selectedRow, 0);

        ViewEmployeeJPanel viewUpdateEmployeeJPanel = new ViewEmployeeJPanel(userProcessContainer, employee);
        userProcessContainer.add("ViewUpdateEmployeeJPanel", viewUpdateEmployeeJPanel);
         ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_viewEmployeeJKButton2ActionPerformed

    private void organizationJComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationJComboBox1ActionPerformed
        Organization o= (Organization) organizationJComboBox1.getSelectedItem();
        if(o!=null){populateEmployeeTable(o);
        addEmployeeJButton1.setEnabled(true);}
        // TODO add your handling code here:
    }//GEN-LAST:event_organizationJComboBox1ActionPerformed

    private void refreshButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButton3ActionPerformed
        Organization o= (Organization) organizationJComboBox1.getSelectedItem();
        if(o!=null)populateEmployeeTable(o);
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmployeeJButton1;
    private javax.swing.JButton backJButton1;
    private javax.swing.JButton deleteEmployeeJButton1;
    private javax.swing.JTable employeeJTable1;
    private javax.swing.JLabel imageJLabel2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameJLabel3;
    private javax.swing.JComboBox organizationJComboBox1;
    private javax.swing.JButton refreshButton3;
    private javax.swing.JLabel selectedEmployeeJLabel6;
    private javax.swing.JButton viewEmployeeJKButton2;
    // End of variables declaration//GEN-END:variables
}
