/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Organizations;

import System.Person.AddressInfo;
import System.Person.Person;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author SURAJ
 */
public class ViewUpdatePersonJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer; 
    private Person person;
    /**
     * Creates new form UpdatePersonJPanel
     */
    public ViewUpdatePersonJPanel(JPanel userProcessContainer, Person p) {
        initComponents();
        this.person=p;
        this.userProcessContainer=userProcessContainer;
        populateFields();
    }

    private void populateFields()
    {
        firstNameJTextField9.setText(person.getFirstName());
        lastNameJTextField10.setText(person.getLastName());
        dobJLabel3.setText(String.valueOf(person.getDay()+" "+ person.getMonth()+" "+String.valueOf(person.getYear())));
        genderJLabel3.setText(person.getGender());
        personIDJLabel4.setText(String.valueOf(person.getPersonID()));
        streetAddress1JTextField1.setText(person.getAddress().getStreetAddress1());
        streetAddress2JTextField2.setText(person.getAddress().getStreetAddress2());
        cityJTextField3.setText(person.getAddress().getCity());
        stateJTextField4.setText(person.getAddress().getState());
        countryJTextField1.setText(person.getAddress().getCountry());
        zipCodeJTextField5.setText(String.valueOf(person.getAddress().getZipCode()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        saveJButton1 = new javax.swing.JButton();
        backJButton1 = new javax.swing.JButton();
        updatePersonJButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        firstNameJLabel10 = new javax.swing.JLabel();
        firstNameJTextField9 = new javax.swing.JTextField();
        lastNameJLabel9 = new javax.swing.JLabel();
        lastNameJTextField10 = new javax.swing.JTextField();
        dobJLabel12 = new javax.swing.JLabel();
        dobJLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        genderJLabel3 = new javax.swing.JLabel();
        personIDJLabel14 = new javax.swing.JLabel();
        personIDJLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        streetAddress1JLabel1 = new javax.swing.JLabel();
        streetAddress1JTextField1 = new javax.swing.JTextField();
        streetAddress2JLabel2 = new javax.swing.JLabel();
        streetAddress2JTextField2 = new javax.swing.JTextField();
        jcityJLabel3 = new javax.swing.JLabel();
        cityJTextField3 = new javax.swing.JTextField();
        stateJLabel4 = new javax.swing.JLabel();
        stateJTextField4 = new javax.swing.JTextField();
        zipCodeJLabel6 = new javax.swing.JLabel();
        countryJTextField1 = new javax.swing.JTextField();
        zipCodeJLabel5 = new javax.swing.JLabel();
        zipCodeJTextField5 = new javax.swing.JTextField();
        imageJLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/View_icon.png"))); // NOI18N
        jLabel5.setText("View/Update Person Profile");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 330, 60));

        saveJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save_icon.gif"))); // NOI18N
        saveJButton1.setText("Save");
        saveJButton1.setToolTipText("Save Details");
        saveJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveJButton1.setEnabled(false);
        saveJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJButton1ActionPerformed(evt);
            }
        });
        add(saveJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 470, 110, 30));

        backJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backbutton.png"))); // NOI18N
        backJButton1.setText("Back");
        backJButton1.setToolTipText("Back");
        backJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });
        add(backJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 100, 30));

        updatePersonJButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset-icon.png"))); // NOI18N
        updatePersonJButton2.setText("Update Person");
        updatePersonJButton2.setToolTipText("Select to Update Person Profile");
        updatePersonJButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updatePersonJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePersonJButton2ActionPerformed(evt);
            }
        });
        add(updatePersonJButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, 160, 30));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "View Profile", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Apple Braille", 1, 14))); // NOI18N
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Step 1 of 2", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Apple Braille", 1, 14), new java.awt.Color(255, 0, 51))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(5, 2, 0, 4));

        firstNameJLabel10.setText("             First Name");
        jPanel1.add(firstNameJLabel10);

        firstNameJTextField9.setEditable(false);
        firstNameJTextField9.setPreferredSize(new java.awt.Dimension(7, 14));
        firstNameJTextField9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstNameJTextField9FocusLost(evt);
            }
        });
        jPanel1.add(firstNameJTextField9);

        lastNameJLabel9.setText("             Last Name");
        jPanel1.add(lastNameJLabel9);

        lastNameJTextField10.setEditable(false);
        lastNameJTextField10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastNameJTextField10FocusLost(evt);
            }
        });
        jPanel1.add(lastNameJTextField10);

        dobJLabel12.setText("             Date of Birth");
        jPanel1.add(dobJLabel12);
        jPanel1.add(dobJLabel3);

        jLabel1.setText("             Gender");
        jPanel1.add(jLabel1);
        jPanel1.add(genderJLabel3);

        personIDJLabel14.setText("             Person ID");
        jPanel1.add(personIDJLabel14);
        jPanel1.add(personIDJLabel4);

        jTabbedPane1.addTab("Personal Information", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Step 2 of 2", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Apple Braille", 1, 14), new java.awt.Color(255, 0, 51))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(6, 2, 0, 1));

        streetAddress1JLabel1.setText("            Street Address 1");
        jPanel2.add(streetAddress1JLabel1);

        streetAddress1JTextField1.setEditable(false);
        jPanel2.add(streetAddress1JTextField1);

        streetAddress2JLabel2.setText("            Street Address 2");
        jPanel2.add(streetAddress2JLabel2);

        streetAddress2JTextField2.setEditable(false);
        jPanel2.add(streetAddress2JTextField2);

        jcityJLabel3.setText("            City");
        jPanel2.add(jcityJLabel3);

        cityJTextField3.setEditable(false);
        cityJTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cityJTextField3FocusLost(evt);
            }
        });
        jPanel2.add(cityJTextField3);

        stateJLabel4.setText("            State");
        jPanel2.add(stateJLabel4);

        stateJTextField4.setEditable(false);
        stateJTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                stateJTextField4FocusLost(evt);
            }
        });
        jPanel2.add(stateJTextField4);

        zipCodeJLabel6.setText("            Country");
        jPanel2.add(zipCodeJLabel6);

        countryJTextField1.setEditable(false);
        countryJTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                countryJTextField1FocusLost(evt);
            }
        });
        jPanel2.add(countryJTextField1);

        zipCodeJLabel5.setText("            ZipCode");
        jPanel2.add(zipCodeJLabel5);

        zipCodeJTextField5.setEditable(false);
        zipCodeJTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                zipCodeJTextField5FocusLost(evt);
            }
        });
        jPanel2.add(zipCodeJTextField5);

        jTabbedPane1.addTab("Address Information", jPanel2);

        jPanel4.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 730, 310));

        imageJLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        imageJLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Organization Background.jpg"))); // NOI18N
        add(imageJLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 690));
    }// </editor-fold>//GEN-END:initComponents

    private void saveJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJButton1ActionPerformed
        
        if(firstNameJTextField9.getText().isEmpty()||lastNameJTextField10.getText().isEmpty()||
              streetAddress1JTextField1.getText().isEmpty() ||cityJTextField3.getText().isEmpty()
                ||stateJTextField4.getText().isEmpty()|| countryJTextField1.getText().isEmpty()
                ||zipCodeJTextField5.getText().isEmpty())
        {
         JOptionPane.showMessageDialog(null, "One or more fields are Empty","", JOptionPane.INFORMATION_MESSAGE);
         return;
        }
        if(zipCodeJTextField5.getText().length()!=5) return;
        if(zipCodeJTextField5.getText().contains("-")||zipCodeJTextField5.getText().contains("+")) return;
        int zipCode;
        try{
            zipCode= Integer.parseInt(zipCodeJTextField5.getText());
         } catch (Exception e) {return;
         }
            AddressInfo address = person.getAddress();
            address.setStreetAddress1(streetAddress1JTextField1.getText());
            address.setStreetAddress2(streetAddress2JTextField2.getText());
            address.setCity(cityJTextField3.getText());
            address.setState(stateJTextField4.getText());
            address.setCountry(countryJTextField1.getText());
            address.setZipCode(zipCode);
            
            person.setFirstName(firstNameJTextField9.getText());
            person.setLastName(lastNameJTextField10.getText());
            person.setAddress(address);
            JOptionPane.showMessageDialog(null, "Person Updated Successfully","", JOptionPane.INFORMATION_MESSAGE);
            userProcessContainer.remove(this);
            ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_saveJButton1ActionPerformed

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_backJButton1ActionPerformed

    private void updatePersonJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePersonJButton2ActionPerformed

        firstNameJTextField9.setEditable(true);
        lastNameJTextField10.setEditable(true);
        streetAddress1JTextField1.setEditable(true);
        streetAddress2JTextField2.setEditable(true);
        cityJTextField3.setEditable(true);
        stateJTextField4.setEditable(true);
        countryJTextField1.setEditable(true);
        zipCodeJTextField5.setEditable(true);
        saveJButton1.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_updatePersonJButton2ActionPerformed

    private void firstNameJTextField9FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameJTextField9FocusLost
        String value = firstNameJTextField9.getText();
        if (value.equals("")) {
        } else {
        Pattern pt6 = Pattern.compile("^[a-zA-Z]*$");
        Matcher mh6 = pt6.matcher(value);
        boolean matchFound6 = mh6.matches();
        if (!(matchFound6)) {
            JOptionPane.showMessageDialog(null, "Enter the Characters only");
            firstNameJTextField9.setText("");
            firstNameJTextField9.requestFocus();
        }
    }     // TODO add your handling code here:
    }//GEN-LAST:event_firstNameJTextField9FocusLost

    private void lastNameJTextField10FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameJTextField10FocusLost
         String value = lastNameJTextField10.getText();
        if (value.equals("")) {
        } else {
        Pattern pt6 = Pattern.compile("^[a-zA-Z]*$");
        Matcher mh6 = pt6.matcher(value);
        boolean matchFound6 = mh6.matches();
        if (!(matchFound6)) {
            JOptionPane.showMessageDialog(null, "Enter the Characters only");
            lastNameJTextField10.setText("");
            lastNameJTextField10.requestFocus();
        }
    } // TODO add your handling code here:
    }//GEN-LAST:event_lastNameJTextField10FocusLost

    private void cityJTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cityJTextField3FocusLost
       String value = cityJTextField3.getText();
        if (value.equals("")) {
        } else {
        Pattern pt6 = Pattern.compile("^[a-zA-Z]*$");
        Matcher mh6 = pt6.matcher(value);
        boolean matchFound6 = mh6.matches();
        if (!(matchFound6)) {
            JOptionPane.showMessageDialog(null, "Enter the Characters only");
            cityJTextField3.setText("");
            cityJTextField3.requestFocus();
        }
    }  // TODO add your handling code here:
    }//GEN-LAST:event_cityJTextField3FocusLost

    private void stateJTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stateJTextField4FocusLost
      String value = stateJTextField4.getText();
        if (value.equals("")) {
        } else {
        Pattern pt6 = Pattern.compile("^[a-zA-Z]*$");
        Matcher mh6 = pt6.matcher(value);
        boolean matchFound6 = mh6.matches();
        if (!(matchFound6)) {
            JOptionPane.showMessageDialog(null, "Enter the Characters only");
            stateJTextField4.setText("");
            stateJTextField4.requestFocus();
        }
    }    // TODO add your handling code here:
    }//GEN-LAST:event_stateJTextField4FocusLost

    private void zipCodeJTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_zipCodeJTextField5FocusLost
       String value = zipCodeJTextField5.getText();
        if (value.equals("")) {
        } else {
        Pattern pt6 = Pattern.compile("^[0-9]*$");
        Matcher mh6 = pt6.matcher(value);
        boolean matchFound6 = mh6.matches();
        if (!(matchFound6)) {
            JOptionPane.showMessageDialog(null, "Enter the Numbers only");
            zipCodeJTextField5.setText("");
            zipCodeJTextField5.requestFocus();
        }else{
            if(value.length()!=5)
            { JOptionPane.showMessageDialog(null, "Enter a 5 digit Zipcode", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
                zipCodeJTextField5.setText("");
                zipCodeJTextField5.requestFocus();
            }
        }
    } // TODO add your handling code here:
    }//GEN-LAST:event_zipCodeJTextField5FocusLost

    private void countryJTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_countryJTextField1FocusLost
        String value = countryJTextField1.getText();
        if (value.equals("")) {
        } else {
            Pattern pt6 = Pattern.compile("^[a-zA-Z]*$");
            Matcher mh6 = pt6.matcher(value);
            boolean matchFound6 = mh6.matches();
            if (!(matchFound6)) {
                JOptionPane.showMessageDialog(null, "Enter the Characters only");
                countryJTextField1.setText("");
                countryJTextField1.requestFocus();
            }
        } // TODO add your handling code here:
    }//GEN-LAST:event_countryJTextField1FocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton1;
    private javax.swing.JTextField cityJTextField3;
    private javax.swing.JTextField countryJTextField1;
    private javax.swing.JLabel dobJLabel12;
    private javax.swing.JLabel dobJLabel3;
    private javax.swing.JLabel firstNameJLabel10;
    private javax.swing.JTextField firstNameJTextField9;
    private javax.swing.JLabel genderJLabel3;
    private javax.swing.JLabel imageJLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jcityJLabel3;
    private javax.swing.JLabel lastNameJLabel9;
    private javax.swing.JTextField lastNameJTextField10;
    private javax.swing.JLabel personIDJLabel14;
    private javax.swing.JLabel personIDJLabel4;
    private javax.swing.JButton saveJButton1;
    private javax.swing.JLabel stateJLabel4;
    private javax.swing.JTextField stateJTextField4;
    private javax.swing.JLabel streetAddress1JLabel1;
    private javax.swing.JTextField streetAddress1JTextField1;
    private javax.swing.JLabel streetAddress2JLabel2;
    private javax.swing.JTextField streetAddress2JTextField2;
    private javax.swing.JButton updatePersonJButton2;
    private javax.swing.JLabel zipCodeJLabel5;
    private javax.swing.JLabel zipCodeJLabel6;
    private javax.swing.JTextField zipCodeJTextField5;
    // End of variables declaration//GEN-END:variables
}
