/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Organizations.FInanceOrganization;

import System.Enterprise.Enterprise;
import System.Organization.Organization;
import System.Person.Person;
import System.UserAccount.EmployeeUserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author SURAJ
 */
public class FinanceEmployeeWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    /**
     * Creates new form FinanceOrganizationWorkAreaJPanel
     */
    public FinanceEmployeeWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, Organization organization, EmployeeUserAccount ua) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.enterprise= enterprise;
        
        for(Person p: organization.getPersonDirectory().getPersonlist())
        if(p.getPersonID()==(ua.getEmployee().getPerson().getPersonID()))
         nameJLabel3.setText(p.getFirstName()+" "+p.getLastName());
        enterpriseNameJLabel2.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewInvoiceHistoryJButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameJLabel3 = new javax.swing.JLabel();
        manageAccountJButton2 = new javax.swing.JButton();
        viewPaymentHistoryJButton2 = new javax.swing.JButton();
        enterpriseNameJLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        imageJLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewInvoiceHistoryJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon_big.gif"))); // NOI18N
        viewInvoiceHistoryJButton1.setText("View Invoice History");
        viewInvoiceHistoryJButton1.setToolTipText("View Invoice History");
        viewInvoiceHistoryJButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewInvoiceHistoryJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewInvoiceHistoryJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewInvoiceHistoryJButton1ActionPerformed(evt);
            }
        });
        add(viewInvoiceHistoryJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 220, 50));

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Finance Employee Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 420, 60));

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 1, 16)); // NOI18N
        jLabel2.setText("Name :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, 30));

        nameJLabel3.setFont(new java.awt.Font("Arial Unicode MS", 1, 16)); // NOI18N
        add(nameJLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 170, 30));

        manageAccountJButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Manage Icon.png"))); // NOI18N
        manageAccountJButton2.setText("Manage Account");
        manageAccountJButton2.setToolTipText("Manage Enterprise Financial Account");
        manageAccountJButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageAccountJButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageAccountJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAccountJButton2ActionPerformed(evt);
            }
        });
        add(manageAccountJButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 220, 50));

        viewPaymentHistoryJButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon_big.gif"))); // NOI18N
        viewPaymentHistoryJButton2.setText("View Payment History");
        viewPaymentHistoryJButton2.setToolTipText("View Payment History");
        viewPaymentHistoryJButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewPaymentHistoryJButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewPaymentHistoryJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPaymentHistoryJButton2ActionPerformed(evt);
            }
        });
        add(viewPaymentHistoryJButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 460, 220, 50));

        enterpriseNameJLabel2.setFont(new java.awt.Font("Arial Unicode MS", 1, 20)); // NOI18N
        add(enterpriseNameJLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, 190, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Financial Graph.jpg"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 800, 190));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/View Folder Icon.png"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 800, 240));

        imageJLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        imageJLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Organization Background.jpg"))); // NOI18N
        add(imageJLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 690));
    }// </editor-fold>//GEN-END:initComponents

    private void manageAccountJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAccountJButton2ActionPerformed

        ManageEnterpriseAccountJPanel manageEnterpriseAccountJPanel= new ManageEnterpriseAccountJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ManageEnterpriseAccountJPanel", manageEnterpriseAccountJPanel);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_manageAccountJButton2ActionPerformed

    private void viewInvoiceHistoryJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewInvoiceHistoryJButton1ActionPerformed

        ViewInvoiceHistoryJPanel viewInvoiceHistoryJPanel= new ViewInvoiceHistoryJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ViewInvoiceHistoryJPanel", viewInvoiceHistoryJPanel);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
// TODO add your handling code here:
    }//GEN-LAST:event_viewInvoiceHistoryJButton1ActionPerformed

    private void viewPaymentHistoryJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPaymentHistoryJButton2ActionPerformed

        ReviewPaymentHistoryJPanel reviewPaymentHistoryJPanel= new ReviewPaymentHistoryJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ReviewPaymentHistoryJPanel", reviewPaymentHistoryJPanel);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_viewPaymentHistoryJButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseNameJLabel2;
    private javax.swing.JLabel imageJLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton manageAccountJButton2;
    private javax.swing.JLabel nameJLabel3;
    private javax.swing.JButton viewInvoiceHistoryJButton1;
    private javax.swing.JButton viewPaymentHistoryJButton2;
    // End of variables declaration//GEN-END:variables
}
