/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Organizations.FInanceOrganization;

import System.Invoice.Invoice;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author SURAJ
 */
public class InvoiceDetailsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Invoice invoice;
    /**
     * Creates new form InvoiceDetailsJPanel
     */
    public InvoiceDetailsJPanel(JPanel userProcessContainer,Invoice invoice) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.invoice=invoice;
        populateFields();
    }
    
    private void populateFields()
    {
        adExchangeLabel10.setText(invoice.getOrder().getExchange());
        advertiserLabel12.setText(invoice.getOrder().getAdvertiser());
        publisherLabel14.setText(invoice.getOrder().getPublisher());
        
        invoiceIDLabel2.setText(String.valueOf(invoice.getInvoiceID()));
        datejLabel3.setText(invoice.getPayment().getDate());
        statusLabel8.setText(invoice.getInvoiceStatus());
        
        adIDLabel14.setText(String.valueOf(invoice.getOrder().getSolutionProvided().getAd().getAdID()));
        amountLabel4.setText(String.valueOf(invoice.getPayment().getTansactionAmount()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        adIDLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        amountLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        invoiceIDLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        datejLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        statusLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        adExchangeLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        advertiserLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        publisherLabel14 = new javax.swing.JLabel();
        imageJLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backbutton.png"))); // NOI18N
        backJButton1.setText("Back");
        backJButton1.setToolTipText("Back");
        backJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });
        add(backJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 600, 80, -1));

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/report-icon-32.png"))); // NOI18N
        jLabel1.setText("Invoice Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 420, 60));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Description", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Apple Braille", 1, 14))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(2, 2, 0, 4));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Advertisment Id :");
        jPanel1.add(jLabel12);
        jPanel1.add(adIDLabel14);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Invoice Amount :");
        jPanel1.add(jLabel3);
        jPanel1.add(amountLabel4);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 630, 120));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Invoice Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Apple Braille", 1, 14))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(3, 2, 0, 4));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Invoice Number :");
        jPanel2.add(jLabel5);
        jPanel2.add(invoiceIDLabel2);

        jLabel6.setText("                          Date/Time :");
        jPanel2.add(jLabel6);
        jPanel2.add(datejLabel3);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Invoice Status :");
        jPanel2.add(jLabel7);
        jPanel2.add(statusLabel8);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 630, 140));

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(3, 2));

        jLabel13.setText("                          AdExchange :");
        jPanel3.add(jLabel13);
        jPanel3.add(adExchangeLabel10);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText(" Advertiser Name :");
        jPanel3.add(jLabel9);
        jPanel3.add(advertiserLabel12);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Publisher Name :");
        jPanel3.add(jLabel11);
        jPanel3.add(publisherLabel14);

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 630, 120));

        imageJLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        imageJLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Organization Background.jpg"))); // NOI18N
        add(imageJLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 690));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed

        userProcessContainer.remove(this);
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_backJButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adExchangeLabel10;
    private javax.swing.JLabel adIDLabel14;
    private javax.swing.JLabel advertiserLabel12;
    private javax.swing.JLabel amountLabel4;
    private javax.swing.JButton backJButton1;
    private javax.swing.JLabel datejLabel3;
    private javax.swing.JLabel imageJLabel2;
    private javax.swing.JLabel invoiceIDLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel publisherLabel14;
    private javax.swing.JLabel statusLabel8;
    // End of variables declaration//GEN-END:variables
}
