/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Organizations.FInanceOrganization;

import System.Enterprise.Enterprise;
import System.FinancialAccount.FinancialAccount;
import java.awt.CardLayout;
import java.text.DecimalFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author SURAJ
 */
public class ManageEnterpriseAccountJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    /**
     * Creates new form ManageEnterpriseAccountsJPanel
     */
    public ManageEnterpriseAccountJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
         this.enterprise= enterprise;
        checkForExistingAccount();
        
    }

    private void checkForExistingAccount()
    {
        if(enterprise.getFinancialAccount().getAccountType()==null)
        {
            accountExistingInfoLabel2.setText("Account Setup Incomplete");
            informtionlabelJLabel3.setText("Select to setup Account :");
            createAccountJButton1.setEnabled(true);
        }
        else{
            detailsJPanel2.setEnabled(true);
            informtionlabelJLabel3.setText("View/Update Account Details");
            updateJButton2.setEnabled(true);
            accountTypeJComboBox1.addItem(enterprise.getFinancialAccount().getAccountType());
            accountNumberjTextField1.setText(String.valueOf(enterprise.getFinancialAccount().getAccountNumber()));
            DecimalFormat df = new DecimalFormat("#.##");
            accountBalanceJTextField1.setText(df.format(enterprise.getFinancialAccount().getAccountBalance()));
         }
    }
    
    private void populateAccountTypeComboBox()
    {
       accountTypeJComboBox1.removeAllItems();
       accountTypeJComboBox1.addItem("Saving Account");
       accountTypeJComboBox1.addItem("Checking Account");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        accountExistingInfoLabel2 = new javax.swing.JLabel();
        informtionlabelJLabel3 = new javax.swing.JLabel();
        detailsJPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        accountTypeJComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        accountNumberjTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        accountBalanceJTextField1 = new javax.swing.JTextField();
        createAccountJButton1 = new javax.swing.JButton();
        backJButton1 = new javax.swing.JButton();
        saveJButton1 = new javax.swing.JButton();
        updateJButton2 = new javax.swing.JButton();
        imageJLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Manage Icon.png"))); // NOI18N
        jLabel1.setText("Manage Financial Accounts");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 420, 60));

        accountExistingInfoLabel2.setFont(new java.awt.Font("Arial Unicode MS", 1, 16)); // NOI18N
        accountExistingInfoLabel2.setForeground(new java.awt.Color(255, 0, 51));
        add(accountExistingInfoLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 360, 30));

        informtionlabelJLabel3.setFont(new java.awt.Font("Arial Unicode MS", 1, 16)); // NOI18N
        add(informtionlabelJLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 280, 30));

        detailsJPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Account Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Apple Braille", 1, 14))); // NOI18N
        detailsJPanel2.setOpaque(false);
        detailsJPanel2.setLayout(new java.awt.GridLayout(3, 2, 0, 4));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Account Type :");
        detailsJPanel2.add(jLabel3);

        accountTypeJComboBox1.setEnabled(false);
        detailsJPanel2.add(accountTypeJComboBox1);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Account Number :");
        detailsJPanel2.add(jLabel5);

        accountNumberjTextField1.setEditable(false);
        accountNumberjTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                accountNumberjTextField1FocusLost(evt);
            }
        });
        detailsJPanel2.add(accountNumberjTextField1);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Amount (in USD):");
        detailsJPanel2.add(jLabel4);

        accountBalanceJTextField1.setEditable(false);
        accountBalanceJTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                accountBalanceJTextField1FocusLost(evt);
            }
        });
        detailsJPanel2.add(accountBalanceJTextField1);

        add(detailsJPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 510, 140));

        createAccountJButton1.setText("Set up Account");
        createAccountJButton1.setToolTipText("Create Enterprise Account");
        createAccountJButton1.setEnabled(false);
        createAccountJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountJButton1ActionPerformed(evt);
            }
        });
        add(createAccountJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 160, 30));

        backJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backbutton.png"))); // NOI18N
        backJButton1.setText("Back");
        backJButton1.setToolTipText("Back");
        backJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });
        add(backJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 80, -1));

        saveJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save_icon.gif"))); // NOI18N
        saveJButton1.setText("Save");
        saveJButton1.setToolTipText("Save Updates");
        saveJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJButton1ActionPerformed(evt);
            }
        });
        add(saveJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, 90, 30));

        updateJButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset-icon.png"))); // NOI18N
        updateJButton2.setText("Update");
        updateJButton2.setToolTipText("Update Account Settings");
        updateJButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateJButton2.setEnabled(false);
        updateJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateJButton2ActionPerformed(evt);
            }
        });
        add(updateJButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 90, 30));

        imageJLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        imageJLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Organization Background.jpg"))); // NOI18N
        add(imageJLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 690));
    }// </editor-fold>//GEN-END:initComponents

    private void createAccountJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountJButton1ActionPerformed

        accountTypeJComboBox1.setEnabled(true);
        accountNumberjTextField1.setEditable(true);
        accountBalanceJTextField1.setEditable(true);
        detailsJPanel2.setEnabled(true);
        populateAccountTypeComboBox();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_createAccountJButton1ActionPerformed

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed

        userProcessContainer.remove(this);
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_backJButton1ActionPerformed

    private void saveJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJButton1ActionPerformed

        if(!(accountBalanceJTextField1.getText().isEmpty()||accountNumberjTextField1.getText().isEmpty()))
        {
        if(accountNumberjTextField1.getText().length()!=10) return;
        if(accountBalanceJTextField1.getText().contains("-")||accountNumberjTextField1.getText().contains("-")
                ||accountNumberjTextField1.getText().contains("+")) 
            return;        
      
        long number;
        double amount;
         try {
             number = Long.parseLong(accountNumberjTextField1.getText());
             amount= Double.parseDouble(accountBalanceJTextField1.getText());
         } catch (Exception e) {return;
         }
        FinancialAccount account=  enterprise.getFinancialAccount();
        account.setAccountType((String) accountTypeJComboBox1.getSelectedItem());
        account.setAccountNumber(number);
        account.setAccountBalance(amount);
        JOptionPane.showMessageDialog(null, "Account Information saved Successfully","", JOptionPane.INFORMATION_MESSAGE);
        userProcessContainer.remove(this);
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
        }else JOptionPane.showMessageDialog(null, "One or more feilds are Empty","", JOptionPane.INFORMATION_MESSAGE);

        // TODO add your handling code here:
    }//GEN-LAST:event_saveJButton1ActionPerformed

    private void updateJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateJButton2ActionPerformed

        populateAccountTypeComboBox();
        accountNumberjTextField1.setEditable(true);
        accountTypeJComboBox1.setEnabled(true);
        accountBalanceJTextField1.setEditable(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_updateJButton2ActionPerformed

    private void accountNumberjTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_accountNumberjTextField1FocusLost

         String value = accountNumberjTextField1.getText();
        if (value.equals("")) {
        } else {
        Pattern pt6 = Pattern.compile("^[0-9]*$");
        Matcher mh6 = pt6.matcher(value);
        boolean matchFound6 = mh6.matches();
        if (!(matchFound6)) {
            JOptionPane.showMessageDialog(null, "Enter the Numbers only");
            accountNumberjTextField1.setText("");
            accountNumberjTextField1.requestFocus();
        }else{
            if(value.length()!=10)
            {   JOptionPane.showMessageDialog(null, "Enter a 10 digit Account Number", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
                accountNumberjTextField1.setText("");
                accountNumberjTextField1.requestFocus();
            }
        }
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_accountNumberjTextField1FocusLost

    private void accountBalanceJTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_accountBalanceJTextField1FocusLost

         String value = accountBalanceJTextField1.getText();
        if (value.equals("")) {
        } else {
        Pattern pt6 = Pattern.compile("^[0-9\\.]*$");
        Matcher mh6 = pt6.matcher(value);
        boolean matchFound6 = mh6.matches();
        if (!(matchFound6)) {
            JOptionPane.showMessageDialog(null, "Enter the Numbers only");
            accountBalanceJTextField1.setText("");
            accountBalanceJTextField1.requestFocus();
        }
    }   // TODO add your handling code here:
    }//GEN-LAST:event_accountBalanceJTextField1FocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountBalanceJTextField1;
    private javax.swing.JLabel accountExistingInfoLabel2;
    private javax.swing.JTextField accountNumberjTextField1;
    private javax.swing.JComboBox accountTypeJComboBox1;
    private javax.swing.JButton backJButton1;
    private javax.swing.JButton createAccountJButton1;
    private javax.swing.JPanel detailsJPanel2;
    private javax.swing.JLabel imageJLabel2;
    private javax.swing.JLabel informtionlabelJLabel3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton saveJButton1;
    private javax.swing.JButton updateJButton2;
    // End of variables declaration//GEN-END:variables
}
