/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Organizations.FInanceOrganization;

import System.Enterprise.Enterprise;
import System.Invoice.Invoice;
import java.awt.CardLayout;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SURAJ
 */
public class ViewInvoiceHistoryJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    /**
     * Creates new form ViewFinancialHistoryJPanel
     */
    public ViewInvoiceHistoryJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.enterprise= enterprise;
        populateInvoiceTable();
    }

    private void populateInvoiceTable()
    {
        DefaultTableModel model = (DefaultTableModel) invoiceJTable1.getModel();
        model.setRowCount(0);
        
        for(Invoice  invoice: enterprise.getInvoiceHistory().getInvoiceList()){
            Object[] row = new Object[5];
            row[0]= invoice;
            row[1]= invoice.getPayment().getDate();
            row[2]= invoice.getOrder().getId();
            DecimalFormat df = new DecimalFormat("#.##");
            row[3]= df.format(invoice.getOrder().getAmount());
            row[4]= invoice.getInvoiceStatus();
            model.addRow(row);
         }   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        invoiceJTable1 = new javax.swing.JTable();
        backJButton1 = new javax.swing.JButton();
        viewDetailsJKButton4 = new javax.swing.JButton();
        imageJLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/report-icon-32.png"))); // NOI18N
        jLabel1.setText("Invoice History");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 420, 60));

        invoiceJTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Invoice ID", "Date/Time", "Order ID", "Invoice Amount", "Invoice Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        invoiceJTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                invoiceJTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(invoiceJTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 770, 360));

        backJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backbutton.png"))); // NOI18N
        backJButton1.setText("Back");
        backJButton1.setToolTipText("Back");
        backJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });
        add(backJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, 90, -1));

        viewDetailsJKButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/View_icon.png"))); // NOI18N
        viewDetailsJKButton4.setText("View Details");
        viewDetailsJKButton4.setToolTipText("View Invoice Details");
        viewDetailsJKButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewDetailsJKButton4.setEnabled(false);
        viewDetailsJKButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsJKButton4ActionPerformed(evt);
            }
        });
        add(viewDetailsJKButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 530, 160, -1));

        imageJLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        imageJLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Organization Background.jpg"))); // NOI18N
        add(imageJLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 690));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed

        userProcessContainer.remove(this);
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_backJButton1ActionPerformed

    private void viewDetailsJKButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsJKButton4ActionPerformed

        int selectedRow= invoiceJTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row","Invalid Action", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Invoice invoice= (Invoice) invoiceJTable1.getValueAt(selectedRow, 0);
        InvoiceDetailsJPanel invoiceDetailsJPanel= new InvoiceDetailsJPanel(userProcessContainer, invoice);
        userProcessContainer.add("InvoiceDetailsJPanel", invoiceDetailsJPanel);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_viewDetailsJKButton4ActionPerformed

    private void invoiceJTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invoiceJTable1MouseClicked
        int selectedRow= invoiceJTable1.getSelectedRow();
        if (selectedRow < 0) return;
        Invoice invoice= (Invoice) invoiceJTable1.getValueAt(selectedRow, 0);
        if(invoice!=null) viewDetailsJKButton4.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_invoiceJTable1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton1;
    private javax.swing.JLabel imageJLabel2;
    private javax.swing.JTable invoiceJTable1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewDetailsJKButton4;
    // End of variables declaration//GEN-END:variables
}
