/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.PublisherEnterprise.AdvertismentPages;

import System.Advertisments.Advertisment;
import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author SURAJ
 */
public class DisplayAdImageJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Advertisment ad;
    /**
     * Creates new form DisplayAdJPanel
     */
    public DisplayAdImageJPanel(JPanel userProcessContainer, Advertisment ad) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.ad=ad;
        displayImage();
    }

    private void displayImage()
    {
        String imagePath= ad.getAdImagePath();
         if (imagePath != null)
          {
           ImageIcon icon= new ImageIcon(imagePath);
           Image img = icon.getImage();
           Image newimg = img.getScaledInstance(800, 550,  java.awt.Image.SCALE_SMOOTH);  
           ImageIcon newIcon = new ImageIcon(newimg); 
           adImageJLabel1.setIcon(newIcon);
          }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adImageJLabel1 = new javax.swing.JLabel();
        backJButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adImageJLabel1.setPreferredSize(new java.awt.Dimension(300, 200));
        add(adImageJLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 930, 550));

        backJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backbutton.png"))); // NOI18N
        backJButton1.setText("Back");
        backJButton1.setToolTipText("Back");
        backJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });
        add(backJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 600, 90, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        userProcessContainer.remove(this);
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_backJButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adImageJLabel1;
    private javax.swing.JButton backJButton1;
    // End of variables declaration//GEN-END:variables
}
